ctrliq/kernel-src-tree

arch/x86/include/asm/page_64.h
arch/x86/include/asm/pgtable_64_types.h
arch/x86/mm/init_64.c
arch/x86/mm/kaslr.c
include/linux/mm.h
kernel/resource.c
mm/memory_hotplug.c
mm/sparse.c
tools/testing/selftests/mm/hmm-tests.c

Bug fix requested by SIG-CLOUD user to address users needs with GPUs, CUDA and HMM.
This is the integration and temporary fix to allow the `HMM` `kselftest` to not live in an infinite loop.
Internal Ticket: SECO-170
```
[maple@r9-sigcloud-builder kernel-src-tree]$ ../kernel-tools/kernel_build.sh
CLEAN   arch/x86/boot/compressed
CLEAN   arch/x86/boot
CLEAN   include/config include/generated arch/x86/include/generated .config .config.old .version Module.symvers certs/signing_key.pem certs/signing_key.x509 certs/x509.genkey
[TIMER]{MRPROPER}: 7s
CONFIG_LOCALVERSION="-jmaple_cuda_bug_fix"
HOSTCC …
```

SIG-CLOUD-9: X86/KASLR fixes for HMM utilized by CUDA + temp fixes/workaround for HMM kselftest

---

.github/workflows/diffdiff.py
.github/workflows/github-actions-demo.yml
.github/workflows/process-git-request.rb
.github/workflows/process-pull-request.yml
.github/workflows/push-check_aarch64.yml
.github/workflows/push-check_x86_64.yml
drivers/net/ethernet/pensando/ionic/ionic_lif.c
include/net/netfilter/nf_tables.h
include/uapi/linux/netfilter/nf_tables.h
net/netfilter/nf_tables_api.c
net/netfilter/nft_flow_offload.c
net/netfilter/nft_objref.c
net/netfilter/nft_quota.c
net/netfilter/nft_set_bitmap.c
net/netfilter/nft_set_hash.c
net/netfilter/nft_set_pipapo.c
net/netfilter/nft_set_rbtree.c

Latest work on the FIPS 8 compliant kernel  Various linked tasks:
VULN-429
VULN-4095
VULN-597
SECO-169
SECO-94
Kernel selftests have passed https://github.com/user-attachments/files/17512330/kernel-selftest.log with no change in results from previous run.
I've been running netfilter tests in a loop overnight - for i in {1..50000}; do sudo valgrind --log-file=valgrind-results$i.log ./run-tests.sh; done
Typical output, unchanged over any number runs.
[nftables-test.log](https://github.com/user-attachments/files/17591163/nftables-test.log)
Valgrind out put from any of hundreds of runs is all the same - 
[valgrind-results.log](https://github.com/user-attachments/files/17591194/valgrind-results.log)
With lockdep enabled and running `sudo stress --cpu 28 --io 28 --vm 28 --vm-bytes 1G --timeout …

Gvrose fips legacy 8 compliant/4.18.0 425.13.1

---

net/mac80211/scan.c

```
wifi: mac80211: Avoid address calculations via out of bounds array in…dexing
jira VULN-6985
cve CVE-2024-41071
commit-author Kenton Groombridge <concord@gentoo.org> commit 2663d0462eb32ae7c9b035300ab6b1523886c718
upstream-diff There is some difference since this knrnel still has `scan_width` support, which is removed in this commit: wifi: cfg80211: remove scan_width support 5add321
req->n_channels must be set before req->channels[] can be used.
This patch fixes one of the issues encountered in [1].
[   83.964255] UBSAN: array-index-out-of-bounds in net/mac80211/scan.c:364:4
[   83.964258] index 0 is out of range for type 'struct ieee80211_channel *[]'
[...]
[   83.964264] Call Trace:
[   83.964267]  <TASK>
[   83.964269]  dump_stack_lvl+0x3f/0xc0
[   83.964274] …
```

[CBR 7.9] CVE-2024-41071

---

net/netfilter/nf_tables_api.c
net/netfilter/nft_dynset.c

Jira VULN-683
Jira VULN-827
```
/home/g.v.rose/prj/kernel-build-tmp
'configs/kernel-4.18.0-x86_64.config' -> '.config'
CONFIG_LOCALVERSION="-debug-branch"
#
#
Starting Build
SYSHDR  arch/x86/include/generated/asm/unistd_32_ia32.h
SYSHDR  arch/x86/include/generated/asm/unistd_64_x32.h
[SNIP]
DEPMOD …
```

PR for CVEs CVE-2023-6622 and CVE-2024-26642

---

include/net/netfilter/nf_tables.h
net/netfilter/nf_tables_api.c
net/netfilter/nft_set_hash.c
net/netfilter/nft_set_pipapo.c
net/netfilter/nft_set_rbtree.c

jira VULN-7047
cve CVE-2024-27397
```
/home/g.v.rose/prj/kernel-build-tmp
'configs/kernel-4.18.0-x86_64.config' -> '.config'
CONFIG_LOCALVERSION="-debug-branch"
#
#
Starting Build
SYSHDR  arch/x86/include/generated/asm/unistd_32_ia32.h
SYSHDR  arch/x86/include/generated/asm/unistd_64_x32.h
SYSTBL …
```

FIPS-8 Legacy: CVE-2024-27397

---

net/netfilter/nf_tables_api.c
net/netfilter/nft_chain_filter.c

This PR will complete LE-2004 and all subsidiary tasks.
Vulnerabilities and CVEs addressed include:
jira VULN-683
cve CVE-2023-6622
jira VULN-827
cve CVE-2024-26642
jira VULN-7047
cve CVE-2024-27397
jira VULN-5238
cve CVE-2024-36005
jira VULN-4905
cve CVE-2024-26925
jira VULN-4905
cve CVE-2024-27020
jira VULN-4961
cve CVE-2024-27019
jira VULN-4985
cve CVE-2024-27065
jira VULN-5126
cve CVE-2024-35899
jira VULN-5134
cve CVE-2024-35900
jira VULN-5118
cve CVE-2024-35897
Builds / install / boots
[build.log](https://github.com/user-attachments/files/17723429/build.log)
[root@lts86-base kernel-build-tmp]# uname -a
Linux lts86-base 4.18.0-debug-branch+ #2 SMP Tue Nov 12 13:01:58 EST 2024 x86_64 x86_64 x86_64 GNU/Linux
Before and after kernel selftest logs: …

PR for completion of LE-2004

---

fs/userfaultfd.c

jira VULN-4370
cve CVE-2021-47461
commit-author Nadav Amit <namit@vmware.com>
commit cb185d5f1ebf900f4ae3bf84cee212e6dd035aca
A race is possible when a process exits, its VMAs are removed by exit_mmap() and at the same time userfaultfd_writeprotect() is called.
The race was detected by KASAN on a development kernel, but it appears to be possible on vanilla kernels as well.
Use mmget_not_zero() to prevent the race as done in other userfaultfd operations.
Link: https://lkml.kernel.org/r/20210921200247.25749-1-namit@vmware.com Fixes: 63b2d4174c4ad ("userfaultfd: wp: add the writeprotect API to userfaultfd ioctl")
Signed-off-by: Nadav Amit <namit@vmware.com>
Tested-by: Li  Wang <liwang@redhat.com>
Reviewed-by: Peter Xu <peterx@redhat.com>
Cc: Andrea Arcangeli <aarcange@redhat.com>
Cc: …

Fix CVE-2021-47461

---

drivers/isdn/mISDN/l1oip.h
drivers/isdn/mISDN/l1oip_core.c

```
jira VULN-168
cve CVE-2022-3565
commit-author Duoming Zhou <duoming@zju.edu.cn>
commit 2568a7e0832ee30b0a351016d03062ab4e0e0a3f
The l1oip_cleanup() traverses the l1oip_ilist and calls release_card() to cleanup module and stack. However, release_card() calls del_timer() to delete the timers such as keep_tl and timeout_tl. If the timer handler is running, the del_timer() will not stop it and result in UAF bugs. One of the processes is shown below:
(cleanup routine)          |        (timer handler)
release_card()                 | l1oip_timeout()
...                           |
del_timer()                   | ...
...                           |
kfree(hc) //FREE              |
| hc->timeout_on = 0 //USE
Fix by calling del_timer_sync() in release_card(), which makes sure the timer …
```

Fix CVE-2022-3565

---

drivers/nvme/target/tcp.c

CVE-2023-5178 for LTS 9.2

---

.github/workflows/process-git-request.rb

A key was exposed in the PR processing ruby script - it was obsolete anyway, but not good form to have it there.

github actions: Fix accidental exposure of key

---

drivers/nvme/target/tcp.c

Fix CVE-2023-5178 lts8.6 RT - VULN-6743

---

include/linux/bpf.h
include/linux/bpf_verifier.h
kernel/bpf/btf.c
kernel/bpf/verifier.c

Vulnerabilities and CVEs addressed include:
jira VULN-72
CVE-2021-4204
jira VULN-144
CVE-2022-23222
jira VULN-7854
CVE-2022-48929
build/install/boot log
[kernel-build.log](https://github.com/user-attachments/files/17907691/kernel-build.log)
[brett@vuln_72_8 ~]$ uname -a
Linux vuln_72_8 4.18.0-CVE-2021-4204+ #1 SMP Fri Nov 22 17:21:12 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
kselftests before and after
[kernel-selftests-before.log](https://github.com/user-attachments/files/17907700/kernel-selftests-before.log)
[kernel-selftests-after.log](https://github.com/user-attachments/files/17907702/kernel-selftests-after.log)
kselftests run with lockdep, kmemleak, and stress
[kernel-selftests-stress-lockdep-kmemleak.log](https://github.com/user-attachments/files/17907706/kernel-selftests-stress-lockde …

SECO-94 completion part 2

---

drivers/nvme/target/tcp.c

CVE-2023-5178 - VULN-3190

---

.github/workflows/process-git-request.rb
drivers/nvme/target/tcp.c

This patch fixes CVE-2023-5178 kernel-rt lts-9.2.
```
nvmet-tcp: Fix a possible UAF in queue intialization setup
jira VULN-6746
cve https://github.com/advisories/GHSA-xr9j-c7v6-7542
commit https://github.com/ctrliq/kernel-src-tree/commit/d920abd1e7c4884f9ecd0749d1921b7ab19ddfbd
From Alon:
"Due to a logical bug in the NVMe-oF/TCP subsystem in the Linux kernel,
a malicious user can cause a UAF and a double free, which may lead to
RCE (may also lead to an LPE in case the attacker already has local
privileges)."
Hence, when a queue initialization fails after the ahash requests are
allocated, it is guaranteed that the queue removal async work will be
called, hence leave the deallocation to the queue removal.
Also, be extra careful not to continue …
```

Fix for CVE-2023-5178 kernel-rt lts-9.2 VULN-6746

---

kernel/bpf/verifier.c

jira VULN-6350
cve CVE-2023-2163
The commit description is too long to practically fit into this PR description.  See the attached original commit for the full commit description.
Builds and installs:
```
/home/g.v.rose/prj/kernel-build-tmp
'configs/kernel-5.14.0-x86_64.config' -> '.config'
CONFIG_LOCALVERSION="-gvrose_ciqlts9_2"
HOSTCC  scripts/kconfig/confdata.o
HOSTCC  scripts/kconfig/expr.o
LEX     scripts/kconfig/lexer.lex.c
YACC    scripts/kconfig/parser.tab.[ch]
HOSTCC  scripts/kconfig/lexer.lex.o
HOSTCC  scripts/kconfig/menu.o
HOSTCC  scripts/kconfig/parser.tab.o
HOSTCC …
```

CVE-2023-2163 kernel lts-9.2 fix

---

tools/testing/selftests/bpf/progs/pyperf180.c

selftests/bpf: Fix pyperf180 compilation failure with clang18

---

.github/workflows/diffdiff.py
.github/workflows/github-actions-demo.yml
.github/workflows/process-git-request.rb
.github/workflows/process-pull-request.yml
.github/workflows/push-check_x86_64.yml
kernel/bpf/verifier.c

A) Install and enable the standard set of github workflows that we use for our other lts branches - pretty straightforward.
B) Address the fix for CVE-2023-2163
Builds and installs:
```
`/home/g.v.rose/prj/kernel-build-tmp
'configs/kernel-4.18.0-x86_64.config' -> '.config'
CONFIG_LOCALVERSION="-gvrose_ciqlts8_8"
#
#
Starting Build
SYSTBL …
```

Fix CVE-2023-2163 for VULN-3181 and enable github workflows

---

tools/testing/selftests/bpf/progs/pyperf180.c

[fips-legacy-8-compliant] selftests/bpf: Fix pyperf180 compilation failure with clang18

---

tools/testing/selftests/bpf/progs/pyperf180.c

[lts8.8-rt] selftests/bpf: Fix pyperf180 compilation failure with clang18

---

tools/testing/selftests/bpf/progs/pyperf180.c

[fips-9-compliant] selftests/bpf: Fix pyperf180 compilation failure with clang18

---

drivers/nvme/target/tcp.c

Fix for CVE-2023-5178 FIPS 9 VULN-6747

---

tools/testing/selftests/bpf/progs/pyperf.h
tools/testing/selftests/bpf/progs/pyperf180.c
tools/testing/selftests/bpf/progs/pyperf600.c

[lts8.6] selftests/bpf: Fix pyperf180 compilation failure with clang18 

---

tools/testing/selftests/bpf/progs/pyperf.h
tools/testing/selftests/bpf/progs/pyperf180.c
tools/testing/selftests/bpf/progs/pyperf600.c

[lts8.6-rt] selftests/bpf: Fix pyperf180 compilation failure with clang18 

---

arch/x86/include/asm/page_64.h
arch/x86/include/asm/pgtable_64_types.h
arch/x86/mm/init_64.c
arch/x86/mm/kaslr.c
include/linux/mm.h
kernel/resource.c
mm/memory_hotplug.c
mm/sparse.c
tools/testing/selftests/mm/hmm-tests.c

* Branch from `centos-stream-9` for the appropriate build `5.14.0-503`
* Kernel History Rebuild Process for all `src.rpm`s hosted by RESF, https://dl.rockylinux.org/vault/rocky/9.5/BaseOS/source/tree/Packages/k/
* Create `sig-cloud-9/5.14.0-503.19.1el9_5` branch
* Cherry-pick all code from pervious branch into new branch (skipping unneeded code) 
* x86/sev-es: Allow copy_from_kernel_nofault() in earlier boot
* Kernel.org[f79936545fb122856bd78b189d3c7ee59928c751](https://github.com/ctrliq/kernel-src-tree/commit/f79936545fb122856bd78b189d3c7ee59928c751)
* CentOS9: kernel-5.14.0-434 https://gitlab.com/redhat/centos-stream/src/kernel/centos-stream-9/-/commit/e638b8e4449ed42a5dcbc …

[sig-cloud-9] 5.14.0-503.19.1.el9_5 update Customer Patches

---

Documentation/atomic_bitops.txt
arch/x86/kernel/cpu/common.c
include/asm-generic/bitops/atomic.h

* Create `sig-cloud-8/4.18.0-553.33.1.el8_10` branch
* None
```
[maple@r8-sigcloud-builder kernel-src-tree]$ ../kernel-tools/kernel_build.sh
CLEAN   .
[SNIP]
CLEAN   include/config usr/include include/generated arch/x86/include/generated
CLEAN   .config .config.old .version Module.symvers
[TIMER]{MRPROPER}: 8s …
```

[sig cloud 8]4.18.0-553.33.1.el8_10 Update Customer Patches

---

kernel/bpf/verifier.c

jira VULN-6600
cve CVE-2023-39191
The fix series for this CVE is here:
https://lore.kernel.org/all/20230121002241.2113993-1-memxor@gmail.com/
However due to the great deal of change in the bpf subsystem between this kernel and 6.3 (where the series landed), backporting this series would require a huge amount of commits to be backported just to apply.
If you look at the changelog for 5.14.0-284.48.1.el9_2 for changes to address CVE-2023-39191 you will only see one entry:
```
- bpf: Fix partial dynptr stack slot reads/writes (Artem Savkov) [2227282 2227283] {CVE-2023-39191}
```
So it would appear RH found the prospect of backporting enough code to land the whole series a bit daunting as well.  As such we have decided to backport this single commit as they did.
```
bpf: Fix partial dynptr …
```

[fips-9] bpf: Fix partial dynptr stack slot reads/writes

---

.github/workflows/diffdiff.py
.github/workflows/github-actions-demo.yml
.github/workflows/process-git-request.rb
.github/workflows/process-pull-request.yml
.github/workflows/push-check_aarch64.yml
.github/workflows/push-check_x86_64.yml
drivers/net/ethernet/mellanox/mlx5/core/en_main.c

This is a pull commits forward from the `4.18.0-425.13.1` FIPS-legacy-8 kernel and set up the githubactions
This change is actually against 2 different Distros 8.6 and 8.10 for FIPS-8-Compliant
```
[maple@r86-fips-553 kernel-src-tree]$ ../kernel-tools/kernel_build.sh
CLEAN   scripts/basic
CLEAN   scripts/genksyms
CLEAN   scripts/kconfig
CLEAN   scripts/mod
CLEAN   scripts/selinux/genheaders
CLEAN   scripts/selinux/mdp
CLEAN   scripts
CLEAN   include/config include/generated arch/x86/include/generated
CLEAN   .config .config.old
[TIMER]{MRPROPER}: 8s
'configs/kernel-4.18.0-x86_64.config' -> '.config'
CONFIG_LOCALVERSION="-_jmaple__fips-8-compliant_4.18.0-553.16.1" …
```

{jmaple} fips 8 compliant/4.18.0 553.16.1

---

kernel/bpf/verifier.c

jira VULN-6598
cve CVE-2023-39191
The fix series for this CVE is here:
https://lore.kernel.org/all/20230121002241.2113993-1-memxor@gmail.com/
However due to the great deal of change in the bpf subsystem between this kernel and 6.3 (where the series landed), backporting this series would require a huge amount of commits to be backported just to apply.
If you look at the changelog for 5.14.0-284.48.1.el9_2 for changes to address https://github.com/advisories/GHSA-gxg7-pxwf-9r28 you will only see one entry:
```
- bpf: Fix partial dynptr stack slot reads/writes (Artem Savkov) [2227282 2227283] {CVE-2023-39191}
```
So it would appear RH found the prospect of backporting enough code to land the whole series a bit daunting as well. As such we have decided to backport this single commit as they …

[lts92] bpf: Fix partial dynptr stack slot reads/writes

---

kernel/bpf/verifier.c

jira VULN-6599
cve https://github.com/advisories/GHSA-gxg7-pxwf-9r28
The fix series for this CVE is here:
https://lore.kernel.org/all/20230121002241.2113993-1-memxor@gmail.com/
However due to the great deal of change in the bpf subsystem between this kernel and 6.3 (where the series landed), backporting this series would require a huge amount of commits to be backported just to apply.
If you look at the changelog for 5.14.0-284.48.1.el9_2 for changes to address https://github.com/advisories/GHSA-gxg7-pxwf-9r28 you will only see one entry:
```
- bpf: Fix partial dynptr stack slot reads/writes (Artem Savkov) [2227282 2227283] {CVE-2023-39191}
```
So it would appear RH found the prospect of backporting enough code to land the whole series a bit daunting as well. As such we have decided to …

[lts9.2-rt] bpf: Fix partial dynptr stack slot reads/writes

---

net/netfilter/nft_set_pipapo.c

jira VULN-8904
```
upstream-diff Additional newline because this kernel has not removed
the nft_set_elem_expired call yet
```
Netfilter selftests were run because this is a netfilter change:
[netfilter-selftest-before.log](https://github.com/user-attachments …

netfilter: nft_set_pipapo: skip inactive elements during set walk

---

include/linux/sched.h

THIS IS BREAKING AND NOT INTENDED TO BE SHIPPED
This is to test the PR checker and the `builders`

Testing Github actions as a contributor

---

.github/workflows/diffdiff.py
.github/workflows/github-actions-demo.yml
.github/workflows/process-git-request.rb
.github/workflows/process-pull-request.yml
.github/workflows/push-check_aarch64.yml
.github/workflows/push-check_x86_64.yml
drivers/nvme/target/tcp.c
kernel/bpf/verifier.c
net/netfilter/nft_set_pipapo.c
tools/testing/selftests/bpf/progs/pyperf180.c

Summary Re-Written by Jonathan Maple (plaidcat) 
This Merge request it to sync `fips-9-compliant/5.14.0-284.30.1` to `fips-9-certified/5.14.0-284.30.1` prior to certification to ensure that the certified kernel has as many CVES from the LTS as we have.  Its also created to show the deltas between the two versions for the Certifying Labs to ensure it does not impact areas of the kernel they're working against.
External context, the kernel team works on LTS updates for compliant as certified is what the Labs are currently looking at so we continue to be able to have new updates for those willing to use "compliant".
This also contains PRs for all Commits
* https://github.com/ctrliq/kernel-src-tree/pull/51
* `netfilter: nft_set_pipapo: skip inactive elements during set walk` 
* …

Fips 9.2 Sync Certified with Compliant.

---

net/bluetooth/l2cap_core.c

jira VULN-206
cve CVE-2022-42896
commit-author Marcin Wcisło <marcin.wcislo@conclusive.pl>
commit f937b758a188d6fd328a81367087eddbb2fce50f
The bug fix in the mainline is provided in two commits:
-   `f937b758a188d6fd328a81367087eddbb2fce50f`
-   `711f8c3fb3db61897080468586b970c87c61d9e4`
Of these the `711f8c3` is already applied on `ciqlts8_8`.
Kernel built on Rocky 9 machine with
CVE=CVE-2022-42896 ./ninja.sh _compile_ciqlts8_8-CVE-2022-42896
from the <https://gitlab.conclusive.pl/devices/rocky-patching> project. This translates to the environment of [Rocky-8-GenericCloud-Base-8.8-20230518.0.x86_64.qcow2](https://download.rockylinux.org/vault/rocky/8.8/images/x86_64/Rocky-8-GenericCloud-Base-8.8-20230518.0.x86_64.qcow2) base image ran with …

[LTS 8.8] Bluetooth: L2CAP: Fix l2cap_global_chan_by_psm

---

.github/workflows/build-check_aarch64.yml
.github/workflows/build-check_x86_64.yml

Since the kernel builds are very expensive we only want to run the workflows associated with them is by approval of staff / maintainers of the kernel.  There was a miss understanding initially that pull_request_target was required to get access to the code.

[LTS 8.8] github actions: Reduce Pull Request openness

---

net/bluetooth/l2cap_core.c

The bug fix in the mainline is provided in two commits:
-   `f937b758a188d6fd328a81367087eddbb2fce50f`
-   `711f8c3fb3db61897080468586b970c87c61d9e4`
Of these the `711f8c3` is already applied on `ciqlts9_2`.
(Same situation as in <https://github.com/ctrliq/kernel-src-tree/pull/41>)
Kernel built on Rocky 9 machine with
CVE=CVE-2022-42896 ./ninja.sh _compile_ciqlts9_2-CVE-2022-42896
from the <https://gitlab.conclusive.pl/devices/rocky-patching> project.
kABI ran on the build machine with
python3 /mnt/code/kernel-dist-git/SOURCES/check-kabi \
-k /mnt/code/kernel-dist-git/SOURCES/Module.kabi_$(uname -m) \
-s /mnt/build_files/kernel-src-tree-ciqlts9_2-CVE-2022-42896/Module.symvers
for the `/mnt/code/kernel-dist-git` repo in the state of
On branch el-9.2
Your branch is up to date with …

[LTS 9.2] Bluetooth: L2CAP: Fix l2cap_global_chan_by_psm

---

include/net/sock.h

This exists in the current delivery spec but is not in the kernel and this work has long since been done, I do not see a public version of the `dist-git` so that will be communicated internally
This is just reading it to the certified and will rebase `fips-9-compliant` off this commit. 
```
net-memcg: avoid stalls when under memory pressure
jira LE-1603
bugfix: cgroupv2 cannot dowload file larger than RAM limit commit-author Jakub Kicinski <kuba@kernel.org>
commit 720ca52bcef225b967a339e0fffb6d0c7e962240
As Shakeel explains the commit under Fixes had the unintended side-effect of no longer pre-loading the cached memory allowance. Even tho we previously dropped the first packet received when over memory limit - the consecutive ones would get thru by using the cache. The charging was …
```

FIPS-9 Add missing code that is included in the RPM but not represented in the kernel src trees

---

.github/workflows/build-check_aarch64-rt.yml
.github/workflows/build-check_aarch64.yml
.github/workflows/build-check_x86_64-rt.yml
.github/workflows/build-check_x86_64.yml

Since we need to make sure external contributors code actually compiles prior to merging. To get access to the forked repos merge request we need to switch over our push to pull_request. In addition we're fixing up some Naming Conventions, adding aarch64 to this branch and fixing the naming so that we can quickly identify if the CI is for x86_64 or aarch64.
Testing with a break and a success
https://github.com/ctrliq/kernel-src-tree/pull/72

[LTS 9.4] github actions: Make Builds on Merge Request Work

---

.github/workflows/build-check_aarch64.yml
.github/workflows/build-check_x86_64.yml

Since we need to make sure external contributors code actually compiles prior to merging. To get access to the forked repos merge request we need to switch over our push to pull_request. In addition we're fixing up some Naming Conventions, adding aarch64 to this branch and fixing the naming so that we can quickly identify if the CI is for x86_64 or aarch64.
Also disable the process-pull-request until the `utf-8` situation is resolved.
Exaple of it working on a PR
https://github.com/ctrliq/kernel-src-tree/pull/75

[LTS 8.6] github actions: Make builds on Merge Request

---

net/bluetooth/l2cap_core.c

The bug fix in the mainline is provided in two commits:
-   `f937b758a188d6fd328a81367087eddbb2fce50f`
-   `711f8c3fb3db61897080468586b970c87c61d9e4`
Of these the `711f8c3` is already applied on `ciqlts9_2-rt` (commit `af424ab54ea3c8a9acce353dd51faf68075c1ce1`).
(Same situation as in <https://github.com/ctrliq/kernel-src-tree/pull/41>)
Kernel built on virtual machine instantiated on physical Rocky 9 machine with
./ninja.sh _run_build-ciqlts9_2
from the <https://gitlab.conclusive.pl/devices/rocky-patching> project. Installed on a testing machine created with
CVE=CVE-2022-42896 ./ninja.sh _run_test-ciqlts9_2-rt-CVE-2022-42896
Logs: [build.log](https://github.com/user-attachments/files/18417205/build.log)
kABI check ran on the build machine with
python3 …

[LTS 9.2-RT] Bluetooth: L2CAP: Fix l2cap_global_chan_by_psm

---

.github/workflows/build-check_x86_64.yml

Since we need to make sure external contributors code actually compiles prior to merging. To get access to the forked repos merge request we need to switch over our push to pull_request. In addition we're fixing up some Naming Conventions, adding aarch64 to this branch and fixing the naming so that we can quickly identify if the CI is for x86_64.
Also disable the process-pull-request until the `utf-8` situation is resolved.
Reference showing the pull request work:
https://github.com/ctrliq/kernel-src-tree/pull/87

[LTS 8.6-rt] github actions: Make builds on Merge Request

---

.github/workflows/build-check_x86_64.yml

Since we need to make sure external contributors code actually compiles prior to merging. To get access to the forked repos merge request we need to switch over our push to pull_request. In addition we're fixing up some Naming Conventions, adding aarch64 to this branch and fixing the naming so that we can quickly identify if the CI is for x86_64 or aarch64.
Reference builds:
https://github.com/ctrliq/kernel-src-tree/pull/85

[LTS 8.8-rt] github actions: Make builds on Merge Request

---

drivers/net/tap.c

[kernel-selftest-baseline-8.6.log](https://github.com/user-attachments/files/18611144/kernel-selftest-baseline-8.6.log)
[kernel-selftest-8.6-patched.log](https://github.com/user-attachments/files/18611146/kernel-selftest-8.6-patched.log)
jira VULN-8269
CVE-2024-41090
The cited commit missed to check against the validity of the frame length in the tap_get_user_xdp() path, which could cause a corrupted skb to be sent downstack. Even before the skb is transmitted, the tap_get_user_xdp()-->skb_set_network_header() may assume the size is more than ETH_HLEN. Once transmitted, this could either cause out-of-bound access beyond the actual length, or confuse the underlayer with incorrect or …

CVE-2024-41090 fix for 8_6_lts.

---

Documentation/atomic_bitops.txt
arch/x86/kernel/cpu/common.c
include/asm-generic/bitops/atomic.h

* Create `sig-cloud-8/4.18.0-553.36.1.el8_10` branch
* None
```
[maple@r8-sigcloud-builder kernel-src-tree]$ ../kernel-src-tree-tools/kernel_build.sh
CONFIG_LOCALVERSION="-_jmaple__sig-cloud-8_4.18.0-553.36.1.el8_10"
YACC …
```

 [SIG CLOUD 8] rebase custom changes to 4.18.0 553.36.1.el8 10

---

net/netfilter/nft_set_pipapo.c

jira VULN-6810
```
upstream-diff Additional newline because this kernel has not removed
the nft_set_elem_expired call yet
```
Same as https://github.com/ctrliq/kernel-src-tree/pull/51
[build.log](https://github.com/user-attachments/files/18647111/build.log) …

[lts92] netfilter: nft_set_pipapo: skip inactive elements during set walk

---

arch/x86/include/asm/page_64.h
arch/x86/include/asm/pgtable_64_types.h
arch/x86/mm/init_64.c
arch/x86/mm/kaslr.c
include/linux/mm.h
kernel/resource.c
mm/memory_hotplug.c
mm/sparse.c
tools/testing/selftests/mm/hmm-tests.c

* Create `sig-cloud-9/ 5.14.0-503.22.1.el9_5` branch
* None
```
[maple@r9-sigcloud-builder kernel-src-tree]$ ../kernel-src-tree-tools/kernel_build.sh
CONFIG_LOCALVERSION="-_jmaple__sig-cloud-9_5.14.0-503.22.1.el9_5"
HOSTCC …
```

[SIG CLOUD 9] rebase custom changes to 5.14.0-503.22.1.el9_5

---

drivers/net/tap.c

[kernel-selftest-baseline-9.2.log](https://github.com/user-attachments/files/18664788/kernel-selftest-baseline-9.2.log)
[kernel-selftest-9.2-patched.log](https://github.com/user-attachments/files/18664792/kernel-selftest-9.2-patched.log)
jira VULN-8274
cve CVE-2024-41090
The cited commit missed to check against the validity of the frame length in the tap_get_user_xdp() path, which could cause a corrupted skb to be sent downstack. Even before the skb is transmitted, the tap_get_user_xdp()-->skb_set_network_header() may assume the size is more than ETH_HLEN. Once transmitted, this could either cause out-of-bound access beyond the actual length, or confuse the underlayer with incorrect or …

tap: add missing verification for short frame

---

.github/workflows/build-check_aarch64.yml
.github/workflows/build-check_x86_64.yml
drivers/media/usb/uvc/uvc_driver.c

jira VULN-9667
```
```
[build.log](https://github.com/user-attachments/files/1870978 …

media: uvcvideo: Skip parsing frames of type UVC_VS_UNDEFINED in uvc_parse_format

---

net/tipc/udp_media.c

jira VULN-8671
cve [CVE-2024-56642](https://github.com/advisories/GHSA-wp52-h62r-qwj4) A patch for a CVE Fix.
Commit that this fixes: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=26abe14379f8
Our matching commit no diff seen: https://github.com/ctrliq/kernel-src-tree/commit/26abe14379f8
```
tipc_net_stop() waits for such works to finish by checking tipc_net(net)->wq_count.  However, the work decrements the count too early before releasing …
```

tipc: Fix use-after-free of kernel socket in cleanup_bearer().

---

drivers/media/usb/uvc/uvc_driver.c

jira VULN-9671
```
```
Same as https://github.com/ctrliq/kernel-src-tree/pull/111 …

[fips-8-legacy] media: uvcvideo: Skip parsing frames of type UVC_VS_UNDEFINED in uvc_parse_format

---

drivers/media/usb/uvc/uvc_driver.c

jira VULN-9668
```
```
Same as https://github.com/ctrliq/kernel-src-tree/pull/111 …

[lts9.4] media: uvcvideo: Skip parsing frames of type UVC_VS_UNDEFINED in uvc_parse_format

---

drivers/media/usb/uvc/uvc_driver.c

jira VULN-9663
```
```
Same as https://github.com/ctrliq/kernel-src-tree/pull/111 …

[lts8.6] media: uvcvideo: Skip parsing frames of type UVC_VS_UNDEFINED in uvc_parse_format

---

drivers/media/usb/uvc/uvc_driver.c

jira VULN-9662
```
```
Same as https://github.com/ctrliq/kernel-src-tree/pull/124 …

[lts8.6-rt] media: uvcvideo: Skip parsing frames of type UVC_VS_UNDEFINED in uvc_parse_format

---

net/tipc/udp_media.c

jira VULN-8672
cve [CVE-2024-56642](https://github.com/advisories/GHSA-wp52-h62r-qwj4)
Commit that this fixes: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=26abe14379f8
Our matching commit no diff seen: https://github.com/ctrliq/kernel-src-tree/commit/26abe14379f8
```
tipc_net_stop() waits for such works to finish by checking tipc_net(net)->wq_count.  However, the work decrements the count too early before releasing the kernel socket, …
```

[LTS 8.8] tipc: Fix use-after-free of kernel socket in cleanup_bearer().

---

net/tipc/udp_media.c

[LTS 9.4] tipc: Fix use-after-free of kernel socket in cleanup_bearer().

---

drivers/net/tap.c

[kernel-selftest-rt-baseline-9.2.log](https://github.com/user-attachments/files/18774609/kernel-selftest-rt-baseline-9.2.log)
[kernel-selftest-rt-patched-9.2.log](https://github.com/user-attachments/files/18774611/kernel-selftest-rt-patched-9.2.log)
[kernel_build_log_9_2_rt.log](https://github.com/user-attachments/files/18774612/kernel_build_log_9_2_rt.log)
$ uname -a
Linux r92rtlts 5.14.0-ciqlts9_2-rt+ #1 SMP PREEMPT_RT Wed Feb 12 00:30:33 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
jira VULN-9073
cve CVE-2024-41090
The cited commit missed to check against the validity of the frame length in the tap_get_user_xdp() path, which could cause a corrupted skb to be sent downstack. Even before the skb …

[lts 9.2-rt] tap: add missing verification for short frame

---

net/tipc/udp_media.c

[fip-8-compliant] tipc: Fix use-after-free of kernel socket in cleanup_bearer().

---

net/tipc/udp_media.c

[fips-9-compliant] tipc: Fix use-after-free of kernel socket in cleanup_bearer().

---

net/sched/sch_hfsc.c

[LTS 8.6 RT]
CVE-2023-4623
VULN-6708
A single commit was identified as a fix for this issue: [b3d26c5702c7d6c45456326e56d2ccf3f103e60f](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b3d26c5702c7d6c45456326e56d2ccf3f103e60f) *net/sched: sch\_hfsc: Ensure …

[LTS 8.6 RT] CVE-2023-4623, VULN-6708

---

net/sched/sch_hfsc.c

[LTS 8.8]
CVE-2023-4623
VULN-6709
A single commit was identified as a fix for this issue: [b3d26c5702c7d6c45456326e56d2ccf3f103e60f](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b3d26c5702c7d6c45456326e56d2ccf3f103e60f) *net/sched: sch\_hfsc: Ensure inner …

[LTS 8.8] CVE-2023-4623, VULN-6709

---

net/tipc/udp_media.c

[fips-legacy-8-compliant] tipc: Fix use-after-free of kernel socket in cleanup_bearer().

---

net/sched/sch_hfsc.c

[LTS 8.8 RT]
CVE-2023-4623
VULN-6710
A single commit was identified as a fix for this issue: [b3d26c5702c7d6c45456326e56d2ccf3f103e60f](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b3d26c5702c7d6c45456326e56d2ccf3f103e60f) *net/sched: sch\_hfsc: Ensure …

[LTS 8.8 RT] CVE-2023-4623, VULN-6710

---

net/sched/sch_hfsc.c

[LTS 9.2]
CVE-2023-4623
VULN-6712
A single commit was identified as a fix for this issue: [b3d26c5702c7d6c45456326e56d2ccf3f103e60f](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b3d26c5702c7d6c45456326e56d2ccf3f103e60f) *net/sched: sch\_hfsc: Ensure inner …

[LTS 9.2] CVE-2023-4623,  VULN-6712

---

net/sched/sch_hfsc.c

[LTS 9.2 RT]
CVE-2023-4623
VULN-6713
A single commit was identified as a fix for this issue: [b3d26c5702c7d6c45456326e56d2ccf3f103e60f](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b3d26c5702c7d6c45456326e56d2ccf3f103e60f) *net/sched: sch\_hfsc: Ensure …

[LTS 9.2 RT] CVE-2023-4623, VULN-6713

---

net/sched/sch_hfsc.c

[LTS 8.6]
CVE-2023-4623
VULN-4106
A single commit was identified as a fix for this issue: [b3d26c5702c7d6c45456326e56d2ccf3f103e60f](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b3d26c5702c7d6c45456326e56d2ccf3f103e60f) *net/sched: sch\_hfsc: Ensure inner …

[LTS 8.6] net/sched: sch_hfsc: upgrade 'rt' to 'sc' when it becomes a inner curve

---

net/tipc/udp_media.c

[ciqlts8_6-rt] tipc: Fix use-after-free of kernel socket in cleanup_bearer().

---

fs/fs-writeback.c
mm/backing-dev.c
mm/page-writeback.c

```
jira VULN-6836
cve CVE-2024-0562
commit-author Khazhismel Kumykov <khazhy@chromium.org> commit f87904c075515f3e1d8f4a7115869d3b914674fd
When a disk is removed, bdi_unregister gets called to stop further writeback and wait for associated delayed work to complete.  However, wb_inode_writeback_end() may schedule bandwidth estimation dwork after this has completed, which can result in the timer attempting to access the just freed bdi_writeback.
Fix this by checking if the bdi_writeback is alive, similar to when scheduling writeback work.
Since this requires wb->work_lock, and wb_inode_writeback_end() may get called from interrupt, switch wb->work_lock to an irqsafe lock.
Link: https://lkml.kernel.org/r/20220801155034.3772543-1-khazhy@google.com Fixes: 45a2966fd641 ("writeback: fix …
```

[ciqlts8_8] writeback: avoid use-after-free after removing device

---

fs/fs-writeback.c
mm/backing-dev.c
mm/page-writeback.c

```
jira VULN-9261
cve CVE-2024-0562
commit-author Khazhismel Kumykov <khazhy@chromium.org> commit f87904c075515f3e1d8f4a7115869d3b914674fd
When a disk is removed, bdi_unregister gets called to stop further writeback and wait for associated delayed work to complete.  However, wb_inode_writeback_end() may schedule bandwidth estimation dwork after this has completed, which can result in the timer attempting to access the just freed bdi_writeback.
Fix this by checking if the bdi_writeback is alive, similar to when scheduling writeback work.
Since this requires wb->work_lock, and wb_inode_writeback_end() may get called from interrupt, switch wb->work_lock to an irqsafe lock.
Link: https://lkml.kernel.org/r/20220801155034.3772543-1-khazhy@google.com Fixes: 45a2966fd641 ("writeback: fix …
```

[ciqlts8_8-rt] writeback: avoid use-after-free after removing device

---

fs/fs-writeback.c
mm/backing-dev.c
mm/page-writeback.c

```
jira VULN-4108
cve CVE-2024-0562
commit-author Khazhismel Kumykov <khazhy@chromium.org> commit f87904c075515f3e1d8f4a7115869d3b914674fd
When a disk is removed, bdi_unregister gets called to stop further writeback and wait for associated delayed work to complete.  However, wb_inode_writeback_end() may schedule bandwidth estimation dwork after this has completed, which can result in the timer attempting to access the just freed bdi_writeback.
Fix this by checking if the bdi_writeback is alive, similar to when scheduling writeback work.
Since this requires wb->work_lock, and wb_inode_writeback_end() may get called from interrupt, switch wb->work_lock to an irqsafe lock.
Link: https://lkml.kernel.org/r/20220801155034.3772543-1-khazhy@google.com Fixes: 45a2966fd641 ("writeback: fix …
```

[ciqlts8_6] writeback: avoid use-after-free after removing device

---

drivers/net/tap.c

[r92ltsfips.ktest-baseline.log](https://github.com/user-attachments/files/19098461/r92ltsfips.ktest-baseline.log)
[r92ltsfips.ktest-baseline.log](https://github.com/user-attachments/files/19098464/r92ltsfips.ktest-baseline.log)
jira VULN-9002
cve CVE-2024-41090
[r92ltsfips.ktest.log](https://github.com/user-attachments/files/19098468/r92ltsfips.ktest.log)
The cited commit missed to check against the validity of the frame length in the tap_get_user_xdp() path, which could cause a corrupted skb to be sent downstack. Even before the skb is transmitted, the tap_get_user_xdp()-->skb_set_network_header() may assume the size is more than ETH_HLEN. Once transmitted, this could either cause …

[FIPS 9.2] tap: add missing verification for short frame

---

net/can/bcm.c

```
jira VULN-36336
cve CVE-2023-52922
commit-author YueHaibing <yuehaibing@huawei.com>
commit 55c3b96074f3f9b0aee19bf93cd71af7516582bb
BUG: KASAN: slab-use-after-free in bcm_proc_show+0x969/0xa80 Read of size 8 at addr ffff888155846230 by task cat/7862
CPU: 1 PID: 7862 Comm: cat Not tainted 6.5.0-rc1-00153-gc8746099c197 #230 Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.15.0-1 04/01/2014 Call Trace:
<TASK>
dump_stack_lvl+0xd5/0x150
print_report+0xc1/0x5e0
kasan_report+0xba/0xf0
bcm_proc_show+0x969/0xa80
seq_read_iter+0x4f6/0x1260
seq_read+0x165/0x210
proc_reg_read+0x227/0x300
vfs_read+0x1d5/0x8d0
ksys_read+0x11e/0x240
do_syscall_64+0x35/0xb0
entry_SYSCALL_64_after_hwframe+0x63/0xcd
Allocated by task 7846:
kasan_save_stack+0x1e/0x40
kasan_set_track+0x21/0x30 …
```

[ciqlts9_2] can: bcm: Fix UAF in bcm_proc_show()

---

include/net/dst_ops.h
include/net/sock.h
net/ipv4/route.c
net/ipv6/route.c
net/xfrm/xfrm_policy.c

[fips-9] net: fix __dst_negative_advice() race

---

Documentation/atomic_bitops.txt
arch/x86/kernel/cpu/common.c
include/asm-generic/bitops/atomic.h

* None
```
CLEAN   .
CLEAN   arch/x86/realmode/rm
CLEAN   arch/x86/lib
CLEAN   certs
CLEAN   drivers/firmware/efi/libstub
CLEAN   drivers/gpu/drm/radeon
CLEAN   drivers/scsi
CLEAN   drivers/tty/vt
CLEAN   drivers/video/logo
CLEAN   kernel/debug/kdb
CLEAN   kernel
CLEAN   lib/raid6
CLEAN   lib
CLEAN   net/wireless
CLEAN …
```

[SIG CLOUD 8] rebase custom changes to 4.18.0-553.40.1.el8_10

---

net/sched/cls_fw.c
net/sched/cls_u32.c

[LTS 9.2 RT]
CVE-2023-4206 VULN-6650
CVE-2023-4207 VULN-6657
CVE-2023-4208 VULN-6664
> 
>  …

[LTS 9.2 RT] CVE-2023-4206, CVE-2023-4207, CVE-2023-4208

---

net/sched/cls_fw.c
net/sched/cls_u32.c

[LTS 9.2]
CVE-2023-4206 VULN-6649
CVE-2023-4207 VULN-6656
CVE-2023-4208 VULN-6663
> 
>  …

[LTS 9.2] CVE-2023-4206, CVE-2023-4207, CVE-2023-4208

---

net/sched/cls_fw.c
net/sched/cls_route.c
net/sched/cls_u32.c

[LTS 8.8 RT]
CVE-2023-4206 VULN-6647
CVE-2023-4207 VULN-6654
CVE-2023-4208 VULN-6661
> 
>  …

[LTS 8.8 RT] CVE-2023-4206, CVE-2023-4207, CVE-2023-4208

---

net/sched/cls_fw.c
net/sched/cls_route.c
net/sched/cls_u32.c

[LTS 8.8]
CVE-2023-4206 VULN-6646
CVE-2023-4207 VULN-6653
CVE-2023-4208 VULN-6660
> 
>  …

[LTS 8.8] CVE-2023-4206, CVE-2023-4207, CVE-2023-4208

---

net/sched/cls_fw.c
net/sched/cls_route.c
net/sched/cls_u32.c

[LTS 8.6 RT]
CVE-2023-4206 VULN-6645
CVE-2023-4207 VULN-6652
CVE-2023-4208 VULN-6659
> 
>  …

[LTS 8.6 RT] CVE-2023-4206, CVE-2023-4207, CVE-2023-4208

---

include/net/dst_ops.h
include/net/sock.h
net/ipv4/route.c
net/ipv6/route.c
net/xfrm/xfrm_policy.c

[lts9.2] net: fix __dst_negative_advice() race

---

include/net/dst_ops.h
include/net/sock.h
net/ipv4/route.c
net/ipv6/route.c
net/xfrm/xfrm_policy.c

[lts8.8] net: fix __dst_negative_advice() race

---

Documentation/networking/xfrm_device.rst
drivers/net/bonding/bond_main.c
drivers/net/ethernet/chelsio/cxgb4/cxgb4_main.c
drivers/net/ethernet/mellanox/mlx5/core/en_accel/ipsec.c
net/xfrm/xfrm_output.c
net/xfrm/xfrm_replay.c

Cherry-picking 4 patches from upstream:
1. [bonding: add ESP offload features when slaves support](https://lore.kernel.org/all/20241105192721.584822-1-tariqt@nvidia.com/)
This patch fixes a perf issue in the bonding driver where ESP segmentation was not being offloaded to the slave devices.
2. [bonding: Correctly support GSO ESP offload](https://lore.kernel.org/netdev/20250127104147.759658-1-cratiu@nvidia.com/)
The fix in patch 1 is incomplete and this change fixes the ESP segmentation issue.
3. [xfrm_output: Force software GSO only in tunnel mode](https://lore.kernel.org/netdev/20250219105248.226962-1-cratiu@nvidia.com/)
Fix in xfrm_output to only trigger software GSO in crypto offload cases for already encapsulated packets in tunnel mode.
4. [xfrm: Support ESN context update to hardware …

Integrate NVidia patches to improve IPSec performance with hw offload

---

include/net/dst_ops.h
include/net/sock.h
net/ipv4/route.c
net/ipv6/route.c
net/xfrm/xfrm_policy.c

[lts86-rt] net: fix __dst_negative_advice() race

---

include/net/dst_ops.h
include/net/sock.h
net/ipv4/route.c
net/ipv6/route.c
net/xfrm/xfrm_policy.c

[lts88-rt] net: fix __dst_negative_advice() race

---

include/net/dst_ops.h
include/net/sock.h
net/ipv4/route.c
net/ipv6/route.c
net/xfrm/xfrm_policy.c

[lts92-rt] net: fix __dst_negative_advice() race

---

drivers/net/tun.c

jira VULN-8272
cve CVE-2024-41091
commit-author Dongli Zhang <dongli.zhang@oracle.com> commit 049584807f1d797fc3078b68035450a9769eb5c3
The cited commit missed to check against the validity of the frame length in the tun_xdp_one() path, which could cause a corrupted skb to be sent downstack. Even before the skb is transmitted, the tun_xdp_one-->eth_type_trans() may access the Ethernet header although it can be less than ETH_HLEN. Once transmitted, this could either cause out-of-bound access beyond the actual length, or confuse the underlayer with incorrect or inconsistent header length in the skb metadata.
In the alternative path, tun_get_user() already prohibits short frame which has the length less than Ethernet header size from being transmitted for IFF_TAP.
This is to drop any frame …

tun: add missing verification for short frame

---

net/mptcp/protocol.c

```
jira VULN-46444
cve CVE-2024-53122
commit-author Paolo Abeni <pabeni@redhat.com>
commit ce7356ae35943cc6494cc692e62d51a734062b7d
Additional active subflows - i.e. created by the in kernel path manager - are included into the subflow list before starting the 3whs.
A racing recvmsg() spooling data received on an already established subflow would unconditionally call tcp_cleanup_rbuf() on all the current subflows, potentially hitting a divide by zero error on the newly created ones.
Explicitly check that the subflow is in a suitable state before invoking tcp_cleanup_rbuf().
Fixes: c76c6956566f ("mptcp: call tcp_cleanup_rbuf on subflows")
Signed-off-by: Paolo Abeni <pabeni@redhat.com>
Reviewed-by: Matthieu Baerts (NGI0) <matttbe@kernel.org>
Link: …
```

mptcp: cope racing subflow creation in mptcp_rcv_space_adjust

---

net/can/bcm.c

```
jira VULN-36332
cve CVE-2023-52922
commit-author YueHaibing <yuehaibing@huawei.com>
commit 55c3b96074f3f9b0aee19bf93cd71af7516582bb
BUG: KASAN: slab-use-after-free in bcm_proc_show+0x969/0xa80 Read of size 8 at addr ffff888155846230 by task cat/7862
CPU: 1 PID: 7862 Comm: cat Not tainted 6.5.0-rc1-00153-gc8746099c197 #230 Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.15.0-1 04/01/2014 Call Trace:
<TASK>
dump_stack_lvl+0xd5/0x150
print_report+0xc1/0x5e0
kasan_report+0xba/0xf0
bcm_proc_show+0x969/0xa80
seq_read_iter+0x4f6/0x1260
seq_read+0x165/0x210
proc_reg_read+0x227/0x300
vfs_read+0x1d5/0x8d0
ksys_read+0x11e/0x240
do_syscall_64+0x35/0xb0
entry_SYSCALL_64_after_hwframe+0x63/0xcd
Allocated by task 7846:
kasan_save_stack+0x1e/0x40
kasan_set_track+0x21/0x30 …
```

[ciqlts8_8] can: bcm: Fix UAF in bcm_proc_show()

---

net/netfilter/nft_set_pipapo.c

jira VULN-6807
```
upstream-diff Additional newline because this kernel has not removed
the nft_set_elem_expired call yet
```
Same as https://github.com/ctrliq/kernel-src-tree/pull/102
Build log
[build.log](https://github.com/user-attachments/files/19507060/ …

[lts8.8] netfilter: nft_set_pipapo: skip inactive elements during set walk

---

net/mptcp/options.c
net/mptcp/protocol.c

Context this has 2 CVES and a bug fix to the same commit as CVE-2024-57882 
Despite MPTCP (MultiPath TCP) is disabled by default we do know that some customers use MultiPath in various ways and can be incredibly difficult to trouble shoot so we're address some additional CVEs outside our priority matrix to make this a little bit better.
https://github.com/ctrliq/kernel-src-tree/pull/181/commits/a562bf3d8b93d0069846e7e8e12c3d4d69c35fa0
A recent change f410cbe introduced in v6.10-rc1 `tcp annotate data-races around tp->window_clamp` had some fuzz due to the WRITE_ONCE and keep the original code.  No conflicts in merged in code.
Note I rebased this to be off the current HEAD after build and test was done.
```
[TIMER]{MRPROPER}: …
```

[FIPS 9.2] mptcp CVEs {CVE-2024-57882,CVE-2024-53122}  + bugfix

---

net/can/bcm.c

```
jira VULN-36337
cve CVE-2023-52922
commit-author YueHaibing <yuehaibing@huawei.com>
commit 55c3b96074f3f9b0aee19bf93cd71af7516582bb
BUG: KASAN: slab-use-after-free in bcm_proc_show+0x969/0xa80 Read of size 8 at addr ffff888155846230 by task cat/7862
CPU: 1 PID: 7862 Comm: cat Not tainted 6.5.0-rc1-00153-gc8746099c197 #230 Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.15.0-1 04/01/2014 Call Trace:
<TASK>
dump_stack_lvl+0xd5/0x150
print_report+0xc1/0x5e0
kasan_report+0xba/0xf0
bcm_proc_show+0x969/0xa80
seq_read_iter+0x4f6/0x1260
seq_read+0x165/0x210
proc_reg_read+0x227/0x300
vfs_read+0x1d5/0x8d0
ksys_read+0x11e/0x240
do_syscall_64+0x35/0xb0
entry_SYSCALL_64_after_hwframe+0x63/0xcd
Allocated by task 7846:
kasan_save_stack+0x1e/0x40
kasan_set_track+0x21/0x30 …
```

[ciqlts9_4] can: bcm: Fix UAF in bcm_proc_show()

---

net/mptcp/options.c
net/mptcp/protocol.c

ontext this has 2 CVES and a bug fix to the same commit as CVE-2024-57882 
Despite MPTCP (MultiPath TCP) is disabled by default we do know that some customers use MultiPath in various ways and can be incredibly difficult to trouble shoot so we're address some additional CVEs outside our priority matrix to make this a little bit better.
https://github.com/ctrliq/kernel-src-tree/pull/181/commits/a562bf3d8b93d0069846e7e8e12c3d4d69c35fa0
A recent change f410cbe introduced in v6.10-rc1 `tcp annotate data-races around tp->window_clamp` had some fuzz due to the WRITE_ONCE and keep the original code.  No conflicts in merged in code.
``` …
```

[LTS 9.2] mptcp CVEs {CVE-2024-57882,CVE-2024-53122} + bugfix

---

net/can/bcm.c

```
jira VULN-36331
cve CVE-2023-52922
commit-author YueHaibing <yuehaibing@huawei.com>
commit 55c3b96074f3f9b0aee19bf93cd71af7516582bb
BUG: KASAN: slab-use-after-free in bcm_proc_show+0x969/0xa80 Read of size 8 at addr ffff888155846230 by task cat/7862
CPU: 1 PID: 7862 Comm: cat Not tainted 6.5.0-rc1-00153-gc8746099c197 #230 Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.15.0-1 04/01/2014 Call Trace:
<TASK>
dump_stack_lvl+0xd5/0x150
print_report+0xc1/0x5e0
kasan_report+0xba/0xf0
bcm_proc_show+0x969/0xa80
seq_read_iter+0x4f6/0x1260
seq_read+0x165/0x210
proc_reg_read+0x227/0x300
vfs_read+0x1d5/0x8d0
ksys_read+0x11e/0x240
do_syscall_64+0x35/0xb0
entry_SYSCALL_64_after_hwframe+0x63/0xcd
Allocated by task 7846:
kasan_save_stack+0x1e/0x40
kasan_set_track+0x21/0x30 …
```

[ciqlts8_6] can: bcm: Fix UAF in bcm_proc_show()

---

net/netfilter/nft_set_pipapo.c

jira VULN-8903
```
upstream-diff The change itself is the same as upstream, but there was
a minor conflict in code surrounding the change because
this kernel hasn't moved set element objects into the
transaction yet.
``` …

[fips-8-legacy] netfilter: nft_set_pipapo: skip inactive elements during set walk

---

net/netfilter/nft_set_pipapo.c

jira VULN-4132
```
upstream-diff The change itself is the same as upstream, but there was
a minor conflict in code surrounding the change because
this kernel hasn't moved set element objects into the
transaction yet.
``` …

[lts-8.6] netfilter: nft_set_pipapo: skip inactive elements during set walk

---

tools/testing/selftests/mm/hmm-tests.c

```
[rolling release update] Checking if any of the commits from the old rolling release are already present in the new base branch
- Commit 77cd727f669fcc8a95d57cff25c1ae3c8d95483d already present in new base branch: 77cd727f669fcc8a95d57cff25c1ae3c8d95483d x86/kaslr: Expose and use the end of the physical memory address space
- CIQ Commit 1347da8e14bc1b35373b6f9511dc44197cf4e586 already present in new base branch: 1347da8e14bc1b35373b6f9511dc44197cf4e586 github actions: …
```

[SIG CLOUD 9] rebase custom changes to 5.14.0-503.29.1.el9_5

---

tools/testing/selftests/mm/hmm-tests.c

Also from https://github.com/ctrliq/kernel-src-tree/pull/209 which was done by mistake.
```
[rolling release update] Checking if any of the commits from the old rolling release are already present in the new base branch
- Commit 77cd727f669fcc8a95d57cff25c1ae3c8d95483d already present in new base branch: 77cd727f669fcc8a95d57cff25c1ae3c8d95483d x86/kaslr: Expose and use the end of the physical memory address space
- CIQ Commit 1347da8e14bc1b35373b6f9511dc44197cf4e586 …
```

[SIG CLOUD 9] rebase custom changes to 5.14.0-503.35.1.el9_5

---

net/can/bcm.c

This PR contains 2 commits. The commit `can: fix CAN BCM build with CONFIG_PROC_FS disabled` adds some required gating for the proc FS functions. And the commit `can: bcm: Fix UAF in bcm_proc_show()` is the actual commit fixing the CVE of ID `CVE-2023-52922`.
There were merge conflicts for both patches cherry picked from upstream due to the CentOS 7.9 kernel being extremely ~~out of date~~ _old_. But both of the merge conflicts were caused by a fuzz mismatch and were easy to resolve by hand.
```
/run/media/kernel/kernel-src-tree
clean   .
clean   arch/x86/kernel/cpu
clean   arch/x86/kernel
clean   arch/x86/purgatory
clean   arch/x86/realmode/rm
clean   arch/x86/vdso
clean   arch/x86/lib
clean   drivers/gpu/drm/radeon
clean   drivers/scsi/aic7xxx
clean   drivers/tty/vt
clean …
```

[ciqcbr7_9] can: bcm: Fix UAF in bcm_proc_show()

---

.github/workflows/build-check_aarch64-rt.yml
.github/workflows/build-check_aarch64.yml
.github/workflows/build-check_x86_64-rt.yml
.github/workflows/build-check_x86_64.yml

* github actions: build-check: Use ./scripts/dummy-tools/ for olddefconfig
LE-2788
Note: configs/kernel*.config are already in sync with dist-git

[lts94]: Use dummy-tools for olddefconfig

---

tools/testing/selftests/mm/hmm-tests.c

* Create `sig-cloud-9/5.14.0-503.38.1.el8_10` branch
None
```
$ python3 rolling-release-update.py --repo ../kernel-src-tree --new-base-branch rocky9_5 --old-rolling-branch sig-cloud-9/5.14.0-503.35.1.el9_5
[rolling release update] Checking out branch:  sig-cloud-9/5.14.0-503.35.1.el9_5
b'c9a24474a2ec (tag: resf_kernel-5.14.0-503.35.1.el9_5) Rebuild rocky9_5 with kernel-5.14.0-503.35.1.el9_5'
b'e74ec186a727 (tag: …
```

[SIG CLOUD 9] rebase custom changes to 5.14.0-503.38.1.el9_5

---

kselftests/README.rst

1.  Description of the key files in kernel's source tree related to running selftests:
-   `tools/testing/selftests/Makefile`
-   `tools/testing/selftests/lib.mk`
-   `tools/testing/selftests/run_kselftest.sh`
-   `tools/testing/selftests/kselftest/runner.sh`
-   `tools/testing/selftests/kselftest-list.txt`
2.  Description of how the tests are organized and how does this abstract organization map to the files and directories in the `tools/testing/selftests/` subdir.
3.  Practical tips for specific use cases
-   Printing the list of all available tests.
-   Running a specific test (instead of the whole collection).
-   Changing the test's timeout.

Initial kselftests README

---

arch/x86/kernel/cpu/common.c

None
```
[rolling release update] Checking out branch:  sig-cloud-8/4.18.0-553.47.1.el8_10
b'01aef32f4a9b (tag: resf_kernel-4.18.0-553.47.1.el8_10) Rebuild rocky8_10 with kernel-4.18.0-553.47.1.el8_10'
b'e622eefa811c (tag: resf_kernel-4.18.0-553.46.1.el8_10) Rebuild rocky8_10 with kernel-4.18.0-553.46.1.el8_10'
b'f025379c5d08 (tag: …
```

[SIG CLOUD 8] rebase custom changes to 4.18.0-553.50.1.el8_10

---

arch/arm64/kernel/cacheinfo.c

[LTS 9.2]
CVE-2025-21785
VULN-54130
<https://www.cve.org/CVERecord?id=CVE-2025-21785>
> In the Linux kernel, the following vulnerability has been resolved: arm64: cacheinfo: Avoid out-of-bounds write to cacheinfo array The loop that detects/populates cache information already has a bounds check on the array size but does not account for cache levels with separate data/instructions cache. Fix this by incrementing the index for any populated leaf (instead of any populated level).
The official fix in the mainline kernel is provided in the 875d742cf5327c93cba1f11e12b08d3cce7a88d2 commit
arm64: cacheinfo: Avoid out-of-bounds write to cacheinfo array
The loop that detects/populates cache information already has a bounds
check on the array size but does not account for cache levels with
separate …

[LTS 9.2] arm64: cacheinfo: Avoid out-of-bounds write to cacheinfo array

---

arch/arm64/kernel/cacheinfo.c

[LTS 8.6]
CVE-2025-21785
VULN-54125
<https://www.cve.org/CVERecord?id=CVE-2025-21785>
> In the Linux kernel, the following vulnerability has been resolved: arm64: cacheinfo: Avoid out-of-bounds write to cacheinfo array The loop that detects/populates cache information already has a bounds check on the array size but does not account for cache levels with separate data/instructions cache. Fix this by incrementing the index for any populated leaf (instead of any populated level).
The official fix in the mainline kernel is provided in the 875d742cf5327c93cba1f11e12b08d3cce7a88d2 commit
arm64: cacheinfo: Avoid out-of-bounds write to cacheinfo array
The loop that detects/populates cache information already has a bounds
check on the array size but does not account for cache levels with
separate …

[LTS 8.6] arm64: cacheinfo: Avoid out-of-bounds write to cacheinfo array

---

.github/workflows/build-check_x86_64.yml

LE-2898
In order to test build the kernel using a centos 7 userspace, we use the rinse tool to create a centos 7 chroot using vault packages. We configure yum to pull packages from vault as well and download the required build tools.  Then we do the same configure and build steps as our other github build checks, except they are run inside the chroot.

[cbr79] [chroot] github actions: Add build check action

---

arch/arm64/kernel/cacheinfo.c
net/sched/sch_hfsc.c

Based off previous CVEs on the standard CIQ LTS kernels:
* CVE-2023-4623 - https://github.com/ctrliq/kernel-src-tree/pull/137
* CVE-2025-21785 - https://github.com/ctrliq/kernel-src-tree/pull/232
The above PR Commits and these were both Clean Cherry Picks from Upstream.
```
$ egrep -B 5 -A 5 "\[TIMER\]|^Starting Build" kbuild.fips-legacy-8-compliant_4.18.0-425.13.1.log
CONFIG_LOCALVERSION="-fips-legacy-8-compliant_4.18.0-425.13.1-54b7326e2d9e"
--
#
#
Starting Build
scripts/kconfig/conf …
```

[FIPS LEGACY 8] CVEs: CVE-2025-21785, CVE-2023-4623

---

drivers/nvme/host/tcp.c

[LTS 8.8]
CVE-2025-21927
VULN-56024
<https://www.cve.org/CVERecord?id=CVE-2025-21927>
> In the Linux kernel, the following vulnerability has been resolved: nvme-tcp: fix potential memory corruption in nvme\_tcp\_recv\_pdu() nvme\_tcp\_recv\_pdu() doesn't check the validity of the header length. When header digests are enabled, a target might send a packet with an invalid header length (e.g. 255), causing nvme\_tcp\_verify\_hdgst() to access memory outside the allocated area and cause memory corruptions by overwriting it with the calculated digest. Fix this by rejecting packets with an unexpected header length.
NVME (Non-Volatile Memory Express) is a communication protocol designed for accessing high-speed storage media, particularly solid-state drives (SSDs). NVMe over Fabrics (NVMe-oF) …

[LTS 8.8] nvme-tcp: fix potential memory corruption in nvme_tcp_recv_pdu()

---

drivers/nvme/host/tcp.c

[LTS 8.6]
CVE-2025-21927
VULN-56023
<https://www.cve.org/CVERecord?id=CVE-2025-21927>
> In the Linux kernel, the following vulnerability has been resolved: nvme-tcp: fix potential memory corruption in nvme\_tcp\_recv\_pdu() nvme\_tcp\_recv\_pdu() doesn't check the validity of the header length. When header digests are enabled, a target might send a packet with an invalid header length (e.g. 255), causing nvme\_tcp\_verify\_hdgst() to access memory outside the allocated area and cause memory corruptions by overwriting it with the calculated digest. Fix this by rejecting packets with an unexpected header length.
NVME (Non-Volatile Memory Express) is a communication protocol designed for accessing high-speed storage media, particularly solid-state drives (SSDs). NVMe over Fabrics (NVMe-oF) …

[LTS 8.6] nvme-tcp: fix potential memory corruption in nvme_tcp_recv_pdu()

---

kselftests/README.rst
kselftests/net/forwarding/README.rst

-   Brief basics for running tests from the `net/forwarding` collection.
-   Added note about the exception of how `kvm` organizes its tests - the testing binaries aren't contained directly in the collection's directory, which confuses the `run_kselftest.sh` script.
-   Fixed a bug in the test names listing snippet - without explicitly setting `SKIP_TARGETS` to nothing some collections may be omitted by the makefile.

Kselftests wiki update

---

drivers/nvme/host/tcp.c

[LTS 9.2]
CVE-2025-21927
VULN-56028
<https://www.cve.org/CVERecord?id=CVE-2025-21927>
> In the Linux kernel, the following vulnerability has been resolved: nvme-tcp: fix potential memory corruption in nvme\_tcp\_recv\_pdu() nvme\_tcp\_recv\_pdu() doesn't check the validity of the header length. When header digests are enabled, a target might send a packet with an invalid header length (e.g. 255), causing nvme\_tcp\_verify\_hdgst() to access memory outside the allocated area and cause memory corruptions by overwriting it with the calculated digest. Fix this by rejecting packets with an unexpected header length.
NVME (Non-Volatile Memory Express) is a communication protocol designed for accessing high-speed storage media, particularly solid-state drives (SSDs). NVMe over Fabrics (NVMe-oF) …

[LTS 9.2] nvme-tcp: fix potential memory corruption in nvme_tcp_recv_pdu()

---

sound/usb/clock.c

```
jira VULN-46532
cve CVE-2024-53150
commit-author Takashi Iwai <tiwai@suse.de>
commit a3dd4d63eeb452cfb064a13862fb376ab108f6a6
The current USB-audio driver code doesn't check bLength of each descriptor at traversing for clock descriptors.  That is, when a device provides a bogus descriptor with a shorter bLength, the driver might hit out-of-bounds reads.
For addressing it, this patch adds sanity checks to the validator functions for the clock descriptor traversal.  When the descriptor length is shorter than expected, it's skipped in the loop.
For the clock source and clock multiplier descriptors, we can just check bLength against the sizeof() of each descriptor type. OTOH, the clock selector descriptor of UAC2 and UAC3 has an array of bNrInPins elements and two more fields at its tail, …
```

[LTS 9.4] ALSA: usb-audio: Fix out of bounds reads when finding clock sources

---

sound/usb/clock.c

```
jira VULN-46532
cve CVE-2024-53150
commit-author Takashi Iwai <tiwai@suse.de>
commit a3dd4d63eeb452cfb064a13862fb376ab108f6a6
The current USB-audio driver code doesn't check bLength of each descriptor at traversing for clock descriptors.  That is, when a device provides a bogus descriptor with a shorter bLength, the driver might hit out-of-bounds reads.
For addressing it, this patch adds sanity checks to the validator functions for the clock descriptor traversal.  When the descriptor length is shorter than expected, it's skipped in the loop.
For the clock source and clock multiplier descriptors, we can just check bLength against the sizeof() of each descriptor type. OTOH, the clock selector descriptor of UAC2 and UAC3 has an array of bNrInPins elements and two more fields at its tail, …
```

{ciqlts9_2} ALSA: usb-audio: Fix out of bounds reads when finding clock sources

---

arch/arm64/kernel/cacheinfo.c
net/sched/sch_hfsc.c

Based off previous CVEs on standard CIQ LTS kernel:
* CVE-2023-4623 - https://github.com/ctrliq/kernel-src-tree/pull/139
* CVE-2025-21785 - https://github.com/ctrliq/kernel-src-tree/pull/219
The above PR Commits and the commits in this PR are all Clean CherryPicks
```
$ egrep -B 5 -A 5 "\[TIMER\]|^Starting Build" kbuild.{jmaple}_fips-9-compliant_5.14.0-284.30.1.log
CONFIG_LOCALVERSION="-_jmaple__fips-9-compliant_5.14.0-284.30.1-1766fca34c70"
--
HOSTCC  scripts/kconfig/util.o
#
#
Starting Build
SYSHDR …
```

[FIPS 9.2 Compliant] CVEs: CVE-2023-4623, CVE-2025-21785

---

net/vmw_vsock/af_vsock.c

VULN-53609
CVE-2025-21756
```
CONFIG_LOCALVERSION="-bmastbergen_ciqlts9_4_VULN-53609-9547bbd702bc"
HOSTCC  scripts/kconfig/confdata.o
HOSTCC  scripts/kconfig/expr.o
LEX     scripts/kconfig/lexer.lex.c
YACC    scripts/kconfig/parser.tab.[ch]
HOSTCC  scripts/kconfig/lexer.lex.o
HOSTCC  scripts/kconfig/menu.o
HOSTCC  scripts/kconfig/parser.tab.o
HOSTCC  scripts/kconfig/preprocess.o
HOSTCC  scripts/kconfig/symbol.o
HOSTCC …
```

[lts-94] vsock fixes for CVE-2025-21756

---

net/vmw_vsock/af_vsock.c

VULN-53607
CVE-2025-21756
```
CONFIG_LOCALVERSION="-b_f-l-8-c_4.18.0-425.13.1_VULN-53607-cfe5078f4f58"
#
#
Starting Build
SYSHDR …
```

[fips-legacy-8] vsock fixes for CVE-2025-21756

---

net/vmw_vsock/af_vsock.c

VULN-53606
CVE-2025-21756
```
CONFIG_LOCALVERSION="-b_f-8-c_4.18.0-553.16.1_VULN-53606-231158bd8156"
#
#
Starting Build
SYSHDR …
```

[fips-8] vsock fixes for CVE-2025-21756

---

net/vmw_vsock/af_vsock.c

VULN-53610
CVE-2025-21756
```
CONFIG_LOCALVERSION="-b_f-9-c_5.14.0-284.30.1_VULN-53610-e910f8fffb5e"
HOSTCC  scripts/kconfig/confdata.o
HOSTCC  scripts/kconfig/expr.o
LEX     scripts/kconfig/lexer.lex.c
YACC    scripts/kconfig/parser.tab.[ch]
HOSTCC  scripts/kconfig/lexer.lex.o
HOSTCC  scripts/kconfig/menu.o
HOSTCC  scripts/kconfig/parser.tab.o
HOSTCC  scripts/kconfig/preprocess.o
HOSTCC  scripts/kconfig/symbol.o
HOSTCC …
```

[fips-9] vsock fixes for CVE-2025-21756

---

drivers/block/xen-blkfront.c
drivers/net/xen-netfront.c
drivers/xen/xenbus/xenbus_xs.c
include/linux/skbuff.h
include/xen/xenbus.h
net/core/skbuff.c

This is four CVE fixes all dealing with Xen and somewhat related, so I've batched them up into a single PR.  It ended up being six commits because I picked up two prereq commits to make the backporting for VULN-1439 and VULN-1039 cleaner.  Both of the prereqs are adding helper functions used by the CVE fixes.
All four of the backported CVE fixes have upstream diffs.  The first two were simple.  The other two were a bit more involved so definitely give them a good look.  There are no Xen selftests in 3.10 and I'm not very familiar with it, so if you think there is any specific testing we can do please let me know.
VULN-1437
VULN-1438
VULN-1439
VULN-1039
CVE-2022-26365
CVE-2022-33740
CVE-2022-33741
CVE-2022-33742
``` …
```

[cbr79] Multiple Xen VULNS

---

arch/arm64/kernel/cacheinfo.c

[LTS 8.8]
CVE-2025-21785
VULN-54126
<https://www.cve.org/CVERecord?id=CVE-2025-21785>
> In the Linux kernel, the following vulnerability has been resolved: arm64: cacheinfo: Avoid out-of-bounds write to cacheinfo array The loop that detects/populates cache information already has a bounds check on the array size but does not account for cache levels with separate data/instructions cache. Fix this by incrementing the index for any populated leaf (instead of any populated level).
The official fix in the mainline kernel is provided in the 875d742cf5327c93cba1f11e12b08d3cce7a88d2 commit
arm64: cacheinfo: Avoid out-of-bounds write to cacheinfo array
The loop that detects/populates cache information already has a bounds
check on the array size but does not account for cache levels with
separate …

[LTS 8.8] arm64: cacheinfo: Avoid out-of-bounds write to cacheinfo array

---

arch/x86/kernel/cpu/common.c

None
```
[jmaple@devbox kernel-src-tree]$ cd ../kernel-src-tree-tools/
[jmaple@devbox kernel-src-tree-tools]$ python3
python3                  python3.11               python3.9                python3.9-config         python3.9-x86_64-config  python3-config
[jmaple@devbox kernel-src-tree-tools]$ python3
python3                  python3.11               python3.9                python3.9-config         python3.9-x86_64-config  python3-config
[jmaple@devbox …
```

[sig-cloud-8] rebase custom changes to 4.18.0-553.51.1.el8_10

---

kselftests/lkdtm/README.rst

Description of the `lkdtm` tests collection available in `9.2` and `9.4`. 
**TLDR**: Doesn't make sense to run them on default builds, because they require some options in the tested kernel which are disabled by default.
**TLDR1**: Even if they are enabled they are likely to crash the machine so they can't be a part of a suite expected to run smoothly.

lkdtm: basic description

---

arch/arm64/kernel/cacheinfo.c

[LTS 9.4]
CVE-2025-21785
VULN-54131
<https://www.cve.org/CVERecord?id=CVE-2025-21785>
> In the Linux kernel, the following vulnerability has been resolved: arm64: cacheinfo: Avoid out-of-bounds write to cacheinfo array The loop that detects/populates cache information already has a bounds check on the array size but does not account for cache levels with separate data/instructions cache. Fix this by incrementing the index for any populated leaf (instead of any populated level).
The official fix in the mainline kernel is provided in the 875d742cf5327c93cba1f11e12b08d3cce7a88d2 commit
arm64: cacheinfo: Avoid out-of-bounds write to cacheinfo array
The loop that detects/populates cache information already has a bounds
check on the array size but does not account for cache levels with
separate …

[LTS 9.4] arm64: cacheinfo: Avoid out-of-bounds write to cacheinfo array

---

drivers/nvme/host/tcp.c

jira VULN-56030
cve CVE-2025-21927
```
commit-author Maurizio Lombardi <mlombard@redhat.com> commit ad95bab0cd28ed77c2c0d0b6e76e03e031391064
upstream-diff Removed `nvme_tcp_c2h_term' case from
`nvme_tcp_recv_pdu_supported' for the sake of consistency of
`nvme_tcp_recv_pdu''s behavior relative to the upstream
version, between the cases of proper and improper
header. (What could be considered as "`c2h_term' type support"
started with 84e009042d0f3dfe91bec60bcd208ee3f866cbcd commit,
not included in `ciqlts9_2''s history, so
`nvme_tcp_recv_pdu_supported' in `ciqlts9_2' shouldn't report
the `nvme_tcp_c2h_term' type as supported.)
nvme_tcp_recv_pdu() doesn't check the validity of the header length. When header digests are enabled, a target might send a packet with an invalid header length (e.g. …
```

[fips9.2] nvme-tcp: fix potential memory corruption in nvme_tcp_recv_pdu()

---

drivers/nvme/host/tcp.c

jira VULN-56026
cve CVE-2025-21927
```
commit-author Maurizio Lombardi <mlombard@redhat.com> commit ad95bab0cd28ed77c2c0d0b6e76e03e031391064
upstream-diff Removed `nvme_tcp_c2h_term' case from
`nvme_tcp_recv_pdu_supported' for the sake of consistency of
`nvme_tcp_recv_pdu''s behavior relative to the upstream
version, between the cases of proper and improper
header. (What could be considered as "`c2h_term' type support"
started with 84e009042d0f3dfe91bec60bcd208ee3f866cbcd commit,
not included in `ciqlts9_2''s history, so
`nvme_tcp_recv_pdu_supported' in `ciqlts9_2' shouldn't report
the `nvme_tcp_c2h_term' type as supported.)
nvme_tcp_recv_pdu() doesn't check the validity of the header length. When header digests are enabled, a target might send a packet with an invalid header length (e.g. …
```

[fips-8.6] nvme-tcp: fix potential memory corruption in nvme_tcp_recv_pdu()

---

drivers/nvme/host/tcp.c

jira VULN-56027
cve CVE-2025-21927
```
commit-author Maurizio Lombardi <mlombard@redhat.com> commit ad95bab0cd28ed77c2c0d0b6e76e03e031391064
upstream-diff Removed `nvme_tcp_c2h_term' case from
`nvme_tcp_recv_pdu_supported' for the sake of consistency of
`nvme_tcp_recv_pdu''s behavior relative to the upstream
version, between the cases of proper and improper
header. (What could be considered as "`c2h_term' type support"
started with 84e009042d0f3dfe91bec60bcd208ee3f866cbcd commit,
not included in `ciqlts9_2''s history, so
`nvme_tcp_recv_pdu_supported' in `ciqlts9_2' shouldn't report
the `nvme_tcp_c2h_term' type as supported.)
nvme_tcp_recv_pdu() doesn't check the validity of the header length. When header digests are enabled, a target might send a packet with an invalid header length (e.g. …
```

[fips-legacy-8] nvme-tcp: fix potential memory corruption in nvme_tcp_recv_pdu()

---

drivers/net/veth.c

jira VULN-67448
cve CVE-2023-53107
```
commit-author Shawn Bohrer <sbohrer@cloudflare.com> commit 7c10131803e45269ddc6c817f19ed649110f3cae
Commit 718a18a0c8a6 ("veth: Rework veth_xdp_rcv_skb in order to accept non-linear skb") introduced a bug where it tried to use pskb_expand_head() if the headroom was less than XDP_PACKET_HEADROOM.  This however uses kmalloc to expand the head, which will later allow consume_skb() to free the skb while is it still in use by AF_XDP.
Previously if the headroom was less than XDP_PACKET_HEADROOM we continued on to allocate a new skb from pages so this restores that behavior.
BUG: KASAN: use-after-free in __xsk_rcv+0x18d/0x2c0 Read of size 78 at addr ffff888976250154 by task napi/iconduit-g/148640
CPU: 5 PID: 148640 Comm: napi/iconduit-g Kdump: loaded …
```

[lts-9.2] veth: Fix use after free in XDP_REDIRECT

---

sound/usb/clock.c

```
jira VULN-46534
cve CVE-2024-53150
commit-author Takashi Iwai <tiwai@suse.de>
commit a3dd4d63eeb452cfb064a13862fb376ab108f6a6
The current USB-audio driver code doesn't check bLength of each descriptor at traversing for clock descriptors.  That is, when a device provides a bogus descriptor with a shorter bLength, the driver might hit out-of-bounds reads.
For addressing it, this patch adds sanity checks to the validator functions for the clock descriptor traversal.  When the descriptor length is shorter than expected, it's skipped in the loop.
For the clock source and clock multiplier descriptors, we can just check bLength against the sizeof() of each descriptor type. OTOH, the clock selector descriptor of UAC2 and UAC3 has an array of bNrInPins elements and two more fields at its tail, …
```

ALSA: usb-audio: Fix out of bounds reads when finding clock sources

---

drivers/net/tun.c

[LTS 8.8]
CVE-2023-3812
VULN-3182
<https://www.cve.org/CVERecord?id=CVE-2023-3812>
> An out-of-bounds memory access flaw was found in the Linux kernel’s TUN/TAP device driver functionality in how a user generates a malicious (too big) networking packet when napi frags is enabled. This flaw allows a local user to crash or potentially escalate their privileges on the system.
The tun/tap devices are enabled in `ciqlts8_8`:
grep '^CONFIG_TUN=' configs/*.config
configs/kernel-aarch64-debug.config:CONFIG_TUN=m
configs/kernel-aarch64.config:CONFIG_TUN=m
configs/kernel-ppc64le-debug.config:CONFIG_TUN=m
configs/kernel-ppc64le.config:CONFIG_TUN=m
configs/kernel-s390x-debug.config:CONFIG_TUN=m
configs/kernel-s390x.config:CONFIG_TUN=m
configs/kernel-x86_64-debug.config:CONFIG_TUN=m …

[LTS 8.8] net: tun: fix bugs for oversize packet when napi frags enabled

---

drivers/net/tun.c

[LTS 9.2]
CVE-2023-3812
VULN-6590
<https://www.cve.org/CVERecord?id=CVE-2023-3812>
> An out-of-bounds memory access flaw was found in the Linux kernel’s TUN/TAP device driver functionality in how a user generates a malicious (too big) networking packet when napi frags is enabled. This flaw allows a local user to crash or potentially escalate their privileges on the system.
The tun/tap devices enabled in `ciqlts9_2`:
grep '^CONFIG_TUN=' configs/*.config
configs/kernel-aarch64-64k-debug-rhel.config:CONFIG_TUN=m
configs/kernel-aarch64-64k-rhel.config:CONFIG_TUN=m
configs/kernel-aarch64-debug-rhel.config:CONFIG_TUN=m
configs/kernel-aarch64-rhel.config:CONFIG_TUN=m
configs/kernel-ppc64le-debug-rhel.config:CONFIG_TUN=m
configs/kernel-ppc64le-rhel.config:CONFIG_TUN=m …

[LTS 9.2] net: tun: fix bugs for oversize packet when napi frags enabled

---

net/vmw_vsock/af_vsock.c

VULN-53608
CVE-2025-21756
Same as https://github.com/ctrliq/kernel-src-tree/pull/250
```
CONFIG_LOCALVERSION="-bmastbergen_ciqlts9_2_VULN-53608-fa32c89ec1b4"
HOSTCC  scripts/kconfig/confdata.o
HOSTCC  scripts/kconfig/expr.o
LEX     scripts/kconfig/lexer.lex.c
YACC    scripts/kconfig/parser.tab.[ch]
HOSTCC  scripts/kconfig/lexer.lex.o
HOSTCC  scripts/kconfig/menu.o
HOSTCC  scripts/kconfig/parser.tab.o
HOSTCC …
```

[lts92] vsock fixes for CVE-2025-21756

---

arch/arm64/kernel/cacheinfo.c

jira VULN-54128
cve CVE-2025-21785
This is an arm64 specific change, which I don't know that we strictly care about in fips branches.  But I don't think it hurts to be in there.  Since there isn't a current aarch64 fips-8.6 kernel to test against I only ran kselftest against the source built kernel under test.  See this PR for lts-8.6 for the same change to see more test results: https://github.com/ctrliq/kernel-src-tree/pull/232
```
commit-author Radu Rendec <rrendec@redhat.com>
commit 875d742cf5327c93cba1f11e12b08d3cce7a88d2
The loop that detects/populates cache information already has a bounds check on the array size but does not account for cache levels with separate data/instructions cache. Fix this by incrementing the index for any populated leaf (instead of any populated level). …
```

[fips-8.6] arm64: cacheinfo: Avoid out-of-bounds write to cacheinfo array

---

drivers/net/tun.c

jira VULN-8828
cve CVE-2023-3812
```
commit-author Ziyang Xuan <william.xuanziyang@huawei.com> commit 363a5328f4b0517e59572118ccfb7c626d81dca9
Recently, we got two syzkaller problems because of oversize packet when napi frags enabled.
One of the problems is because the first seg size of the iov_iter from user space is very big, it is 2147479538 which is bigger than the threshold value for bail out early in __alloc_pages(). And skb->pfmemalloc is true, __kmalloc_reserve() would use pfmemalloc reserves without __GFP_NOWARN flag. Thus we got a warning as following:
======================================================== WARNING: CPU: 1 PID: 17965 at mm/page_alloc.c:5295 __alloc_pages+0x1308/0x16c4 mm/page_alloc.c:5295 ...
Call trace:
__alloc_pages+0x1308/0x16c4 mm/page_alloc.c:5295 …
```

[fips-9] net: tun: fix bugs for oversize packet when napi frags enabled

---

net/sched/cls_u32.c

jira VULN-6548
cve CVE-2023-3609
```
commit-author Lee Jones <lee@kernel.org>
commit 04c55383fa5689357bcdd2c8036725a55ed632bc
In the event of a failure in tcf_change_indev(), u32_set_parms() will immediately return without decrementing the recently incremented reference counter.  If this happens enough times, the counter will rollover and the reference freed, leading to a double free which can be used to do 'bad things'.
In order to prevent this, move the point of possible failure above the point where the reference counter is incremented.  Also save any meaningful return values to be applied to the return data at the appropriate point in time.
This issue was caught with KASAN.
Fixes: 705c7091262d ("net: sched: cls_u32: no need to call tcf_exts_change for newly allocated struct") …
```

[lts-9.2] net/sched: cls_u32: Fix reference counter leak leading to overflow

---

net/sched/cls_u32.c

jira VULN-8824
cve CVE-2023-3609
```
commit-author Lee Jones <lee@kernel.org>
commit 04c55383fa5689357bcdd2c8036725a55ed632bc
In the event of a failure in tcf_change_indev(), u32_set_parms() will immediately return without decrementing the recently incremented reference counter.  If this happens enough times, the counter will rollover and the reference freed, leading to a double free which can be used to do 'bad things'.
In order to prevent this, move the point of possible failure above the point where the reference counter is incremented.  Also save any meaningful return values to be applied to the return data at the appropriate point in time.
This issue was caught with KASAN.
Fixes: 705c7091262d ("net: sched: cls_u32: no need to call tcf_exts_change for newly allocated struct") …
```

[fips-9-compliant] net/sched: cls_u32: Fix reference counter leak leading to overflow

---

drivers/net/tun.c

jira VULN-8777
cve CVE-2022-4744
```
commit-author George Kennedy <george.kennedy@oracle.com> commit 158b515f703e75e7d68289bf4d98c664e1d632df
upstream-diff Content is the same as the upstream patch except
s/dev->tstats/tun->pcpu_stats/g becuase the switch to
tstats (497a5757ce4e "tun: switch to net core provided
statistics counters") isn't in this kernel.
This matches how this change was backported to 4.19.y.
Avoid double free in tun_free_netdev() by moving the dev->tstats and tun->security allocs to a new ndo_init routine (tun_net_init()) that will be called by register_netdevice(). ndo_init is paired with the desctructor (tun_free_netdev()), so if there's an error in register_netdevice() the destructor will handle the frees.
BUG: KASAN: double-free or invalid-free in …
```

[fips-legacy-8] tun: avoid double free in tun_free_netdev

---

arch/x86/kernel/cpu/common.c

* Create `sig-cloud-8/4.18.0-553.53.1.el8_10` branch
None
```
[jmaple@devbox kernel-src-tree-tools]$ python3 rolling-release-update.py --repo ../kernel-src-tree/ --new-base-branch rocky8_10 --old-rolling-branch sig-cloud-8/4.18.0-553.51.1.el8_10
[rolling release update] Checking out branch:  sig-cloud-8/4.18.0-553.51.1.el8_10
b'bda8b8ebc7b7 (tag: resf_kernel-4.18.0-553.51.1.el8_10) Rebuild rocky8_10 with …
```

[sig-cloud-8] rebase custom changes to 4.18.0-553.53.1.el8_10

---

net/ipv4/inet_connection_sock.c
net/ipv4/tcp_ulp.c

[LTS 8.6]
CVE-2023-0461
VULN-3655
<https://www.cve.org/CVERecord?id=CVE-2023-0461>
> There is a use-after-free vulnerability in the Linux Kernel which can be exploited to achieve local privilege escalation. To reach the vulnerability kernel configuration flag CONFIG\_TLS or CONFIG\_XFRM\_ESPINTCP has to be configured, but the operation does not require any privilege. There is a use-after-free bug of icsk\_ulp\_data of a struct inet\_connection\_sock. When CONFIG\_TLS is enabled, user can install a tls context (struct tls\_context) on a connected tcp socket. The context is not cleared if this socket is disconnected and reused as a listener. If a new socket is created from the listener, the context is inherited and vulnerable. The setsockopt TCP\_ULP operation does not require any …

[LTS 8.6] net/ulp: use consistent error code when blocking ULP

---

net/sched/cls_u32.c

jira VULN-6545
cve CVE-2023-3609
```
commit-author Lee Jones <lee@kernel.org>
commit 04c55383fa5689357bcdd2c8036725a55ed632bc
In the event of a failure in tcf_change_indev(), u32_set_parms() will immediately return without decrementing the recently incremented reference counter.  If this happens enough times, the counter will rollover and the reference freed, leading to a double free which can be used to do 'bad things'.
In order to prevent this, move the point of possible failure above the point where the reference counter is incremented.  Also save any meaningful return values to be applied to the return data at the appropriate point in time.
This issue was caught with KASAN.
Fixes: 705c7091262d ("net: sched: cls_u32: no need to call tcf_exts_change for newly allocated struct") …
```

[lts-8.8] net/sched: cls_u32: Fix reference counter leak leading to overflow

---

net/tipc/msg.c

[LTS 8.6]
CVE-2024-36886
VULN-5314
<https://www.zerodayinitiative.com/advisories/ZDI-24-821/>
> This vulnerability allows remote attackers to execute arbitrary code on affected installations of Linux Kernel. Authentication is not required to exploit this vulnerability, but only systems with TIPC bearer enabled are vulnerable.
> The specific flaw exists within the processing of fragmented TIPC messages. The issue results from the lack of validating the existence of an object prior to performing operations on the object. An attacker can leverage this vulnerability to execute code in the context of the kernel.
The vulnerability applies to `ciqlts8_6` as the `tipc` module is enabled:
`configs/kernel-x86_64.config`:
CONFIG_TIPC=m
CONFIG_TIPC_CRYPTO=y
CONFIG_TIPC_DIAG=m
CONFIG_TIPC_MEDIA_IB=y …

[LTS 8.6] tipc: fix UAF in error path

---

net/tipc/msg.c

[LTS 8.8]
CVE-2024-36886
VULN-5316
<https://www.zerodayinitiative.com/advisories/ZDI-24-821/>
> This vulnerability allows remote attackers to execute arbitrary code on affected installations of Linux Kernel. Authentication is not required to exploit this vulnerability, but only systems with TIPC bearer enabled are vulnerable. 
> The specific flaw exists within the processing of fragmented TIPC messages. The issue results from the lack of validating the existence of an object prior to performing operations on the object. An attacker can leverage this vulnerability to execute code in the context of the kernel.
The vulnerability applies to `ciqlts8_8` as the `tipc` module is enabled:
`configs/kernel-x86_64.config`:
CONFIG_TIPC=m
CONFIG_TIPC_CRYPTO=y
CONFIG_TIPC_DIAG=m
CONFIG_TIPC_MEDIA_IB=y …

[LTS 8.8] tipc: fix UAF in error path

---

net/tipc/msg.c

[LTS 9.2]
CVE-2024-36886
VULN-5319
<https://www.zerodayinitiative.com/advisories/ZDI-24-821/>
> This vulnerability allows remote attackers to execute arbitrary code on affected installations of Linux Kernel. Authentication is not required to exploit this vulnerability, but only systems with TIPC bearer enabled are vulnerable. 
> The specific flaw exists within the processing of fragmented TIPC messages. The issue results from the lack of validating the existence of an object prior to performing operations on the object. An attacker can leverage this vulnerability to execute code in the context of the kernel.
The vulnerability applies to `ciqlts9_2` as the `tipc` module is enabled:
`configs/kernel-x86_64-rhel.config`:
CONFIG_TIPC_CRYPTO=y
CONFIG_TIPC_DIAG=m
CONFIG_TIPC=m …

[LTS 9.2] tipc: fix UAF in error path

---

drivers/net/ethernet/intel/igb/igb_main.c

[LTS 8.8]
CVE-2023-45871
VULN-6695
From the company which discovered the bug:
<https://www.omicronenergy.com/download/file/5ddf37266b0d79a7ba5818893202d9c1/>
> Linux Kernel vulnerability CVE-2023-45871 allows an attacker to cause memory corruption in the network driver of the \*BX device by sending special crafted network traffic. The behaviour of the system caused by memory corruption is highly unpredictable: the device is either restarted, processes crash, or a manual reboot is required.
The CVSS 3.1 scoring is somewhat inconsistent, ranging from 7.5 ([nist](https://nvd.nist.gov/vuln/detail/CVE-2023-45871)) to 9.8 (above).
The `igb` module is enabled in `ciqlts8_8`
`configs/kernel-x86_64.config`
CONFIG_IGB=m
CONFIG_IGBVF=m
CONFIG_IGB_DCA=y
CONFIG_IGB_HWMON=y
The mainline fix is given in …

[LTS 8.8] igb: set max size RX buffer when store bad packet is enabled

---

drivers/net/ethernet/intel/igb/igb_main.c

[LTS 9.2]
CVE-2023-45871
VULN-6698
From the company which discovered the bug:
<https://www.omicronenergy.com/download/file/5ddf37266b0d79a7ba5818893202d9c1/>
> Linux Kernel vulnerability CVE-2023-45871 allows an attacker to cause memory corruption in the network driver of the \*BX device by sending special crafted network traffic. The behaviour of the system caused by memory corruption is highly unpredictable: the device is either restarted, processes crash, or a manual reboot is required.
The CVSS 3.1 scoring is somewhat inconsistent, ranging from 7.5 ([nist](https://nvd.nist.gov/vuln/detail/CVE-2023-45871)) to 9.8 (above).
The `igb` module is enabled in `ciqlts9_2`
`configs/kernel-x86_64-rhel.config`:
CONFIG_IGB_DCA=y
CONFIG_IGB_HWMON=y
CONFIG_IGB=m
CONFIG_IGBVF=m
The mainline fix is …

[LTS 9.2] igb: set max size RX buffer when store bad packet is enabled

---

net/netfilter/ipset/ip_set_bitmap_ip.c

```
jira VULN-46557
cve CVE-2024-53141
commit-author Jeongjun Park <aha310510@gmail.com>
commit 35f56c554eb1b56b77b3cf197a6b00922d49033d
When tb[IPSET_ATTR_IP_TO] is not present but tb[IPSET_ATTR_CIDR] exists, the values of ip and ip_to are slightly swapped. Therefore, the range check for ip should be done later, but this part is missing and it seems that the vulnerability occurs.
So we should add missing range checks and remove unnecessary range checks.
Cc: <stable@vger.kernel.org>
Reported-by: syzbot+58c872f7790a4d2ac951@syzkaller.appspotmail.com
Fixes: 72205fc68bd1 ("netfilter: ipset: bitmap:ip set type support")
Signed-off-by: Jeongjun Park <aha310510@gmail.com>
Acked-by: Jozsef Kadlecsik <kadlec@blackhole.kfki.hu>
(cherry picked …
```

netfilter: ipset: add missing range check in bitmap_ip_uadt

---

net/sched/sch_qfq.c

jira VULN-8813
cve CVE-2023-31436
```
commit-author Gwangun Jung <exsociety@gmail.com>
commit 3037933448f60f9acb705997eae62013ecb81e0d
If the TCA_QFQ_LMAX value is not offered through nlattr, lmax is determined by the MTU value of the network device. The MTU of the loopback device can be set up to 2^31-1. As a result, it is possible to have an lmax value that exceeds QFQ_MIN_LMAX.
Due to the invalid lmax value, an index is generated that exceeds the QFQ_MAX_INDEX(=24) value, causing out-of-bounds read/write errors.
The following reports a oob access:
[   84.582666] BUG: KASAN: slab-out-of-bounds in qfq_activate_agg.constprop.0 (net/sched/sch_qfq.c:1027 net/sched/sch_qfq.c:1060 net/sched/sch_qfq.c:1313)
[   84.583267] Read of size 4 at addr ffff88810f676948 by task ping/301
[   84.583686] …
```

[fips-legacy-8] net: sched: sch_qfq: prevent slab-out-of-bounds in qfq_activate_agg

---

drivers/net/tap.c

```
jira VULN-9000
cve CVE-2024-41090
The cited commit missed to check against the validity of the frame length in the tap_get_user_xdp() path, which could cause a corrupted skb to be sent downstack. Even before the skb is transmitted, the tap_get_user_xdp()-->skb_set_network_header() may assume the size is more than ETH_HLEN. Once transmitted, this could either cause out-of-bound access beyond the actual length, or confuse the underlayer with incorrect or inconsistent header length in the skb metadata.
In the alternative path, tap_get_user() already prohibits short frame which has the length less than Ethernet header size from being transmitted.
This is to drop any frame shorter than the …
```

[fips 8.6] tap: add missing verification for short frame

---

net/netfilter/ipset/ip_set_bitmap_ip.c

```
jira VULN-46558
cve CVE-2024-53141
commit-author Jeongjun Park <aha310510@gmail.com>
commit 35f56c554eb1b56b77b3cf197a6b00922d49033d
When tb[IPSET_ATTR_IP_TO] is not present but tb[IPSET_ATTR_CIDR] exists, the values of ip and ip_to are slightly swapped. Therefore, the range check for ip should be done later, but this part is missing and it seems that the vulnerability occurs.
So we should add missing range checks and remove unnecessary range checks.
Cc: <stable@vger.kernel.org>
Reported-by: syzbot+58c872f7790a4d2ac951@syzkaller.appspotmail.com
Fixes: 72205fc68bd1 ("netfilter: ipset: bitmap:ip set type support")
Signed-off-by: Jeongjun Park <aha310510@gmail.com>
Acked-by: Jozsef Kadlecsik <kadlec@blackhole.kfki.hu>
(cherry picked …
```

[fips 9.2] netfilter: ipset: add missing range check in bitmap_ip_uadt

---

drivers/dma/idxd/irq.c

jira VULN-8254
cve CVE-2024-40956
```
commit-author Li RongQing <lirongqing@baidu.com>
commit e3215deca4520773cd2b155bed164c12365149a7
Use list_for_each_entry_safe() to allow iterating through the list and deleting the entry in the iteration process. The descriptor is freed via idxd_desc_complete() and there's a slight chance may cause issue for the list iterator when the descriptor is reused by another thread without it being deleted from the list.
Fixes: 16e19e11228b ("dmaengine: idxd: Fix list corruption in description completion")
Signed-off-by: Li RongQing <lirongqing@baidu.com>
Reviewed-by: Dave Jiang <dave.jiang@intel.com>
Reviewed-by: Fenghua Yu <fenghua.yu@intel.com>
Link: https://lore.kernel.org/r/20240603012444.11902-1-lirongqing@baidu.com
Signed-off-by: Vinod Koul …
```

[lts-9.2] dmaengine: idxd: Fix possible Use-After-Free in irq_process_work_list

---

net/sched/sch_qfq.c

jira VULN-6468
cve CVE-2023-31436
Same as https://github.com/ctrliq/kernel-src-tree/pull/308
```
commit-author Gwangun Jung <exsociety@gmail.com>
commit 3037933448f60f9acb705997eae62013ecb81e0d
If the TCA_QFQ_LMAX value is not offered through nlattr, lmax is determined by the MTU value of the network device. The MTU of the loopback device can be set up to 2^31-1. As a result, it is possible to have an lmax value that exceeds QFQ_MIN_LMAX.
Due to the invalid lmax value, an index is generated that exceeds the QFQ_MAX_INDEX(=24) value, causing out-of-bounds read/write errors.
The following reports a oob access:
[   84.582666] BUG: KASAN: slab-out-of-bounds in qfq_activate_agg.constprop.0 (net/sched/sch_qfq.c:1027 net/sched/sch_qfq.c:1060 net/sched/sch_qfq.c:1313)
[   84.583267] Read of size …
```

[lts88] net: sched: sch_qfq: prevent slab-out-of-bounds in qfq_activate_agg

---

net/sched/sch_qfq.c

jira VULN-8822
cve CVE-2023-3611
```
commit-author Pedro Tammela <pctammela@mojatatu.com> commit 3e337087c3b5805fe0b8a46ba622a962880b5d64
upstream-diff used linux-stable LT-4.19 sha ee3bc829f9b4df96d208d58b654e400fa1f3b46c
commit 3e337087c3b5805fe0b8a46ba622a962880b5d64 upstream.
Lion says:
-------
In the QFQ scheduler a similar issue to CVE-2023-31436 persists.
Consider the following code in net/sched/sch_qfq.c:
static int qfq_enqueue(struct sk_buff *skb, struct Qdisc *sch,
struct sk_buff **to_free)
{
unsigned int len = qdisc_pkt_len(skb), gso_segs;
// ...
if (unlikely(cl->agg->lmax < len)) {
pr_debug("qfq: increasing maxpkt from %u to %u for class %u",
cl->agg->lmax, len, cl->common.classid);
err = qfq_change_agg(sch, cl, cl->agg->class_weight, len);
if (err) {
cl->qstats.drops++; …
```

[fips-legacy-8] net/sched: sch_qfq: account for stab overhead in qfq_enqueue

---

net/netfilter/ipset/ip_set_bitmap_ip.c

```
jira VULN-46554
cve CVE-2024-53141
commit-author Jeongjun Park <aha310510@gmail.com>
commit 35f56c554eb1b56b77b3cf197a6b00922d49033d
When tb[IPSET_ATTR_IP_TO] is not present but tb[IPSET_ATTR_CIDR] exists, the values of ip and ip_to are slightly swapped. Therefore, the range check for ip should be done later, but this part is missing and it seems that the vulnerability occurs.
So we should add missing range checks and remove unnecessary range checks.
Cc: <stable@vger.kernel.org>
Reported-by: syzbot+58c872f7790a4d2ac951@syzkaller.appspotmail.com
Fixes: 72205fc68bd1 ("netfilter: ipset: bitmap:ip set type support")
Signed-off-by: Jeongjun Park <aha310510@gmail.com>
Acked-by: Jozsef Kadlecsik <kadlec@blackhole.kfki.hu>
(cherry picked …
```

[fips-8.6] netfilter: ipset: add missing range check in bitmap_ip_uadt

---

drivers/nvme/target/tcp.c

[lts88] nvmet-tcp: Fix a possible UAF in queue intialization setup

---

tools/testing/selftests/mm/hmm-tests.c

* Create `sig-cloud-9/5.14.0-570.X.1.el8_10` branch
None
```
[jmaple@devbox kernel-src-tree-tools]$ python3 rolling-release-update.py --repo ../kernel-src-tree --new-base-branch rocky9_6 --old-rolling-branch sig-cloud-9/5.14.0-570.18.1.el9_6
[rolling release update] Checking out branch:  sig-cloud-9/5.14.0-570.18.1.el9_6
b'e8b954c95fef (tag: resf_kernel-5.14.0-570.18.1.el9_6, …
```

[SIG-CLOUD-9] rebase custom changes to 5.14.0-570.19.1

---

drivers/net/ethernet/microsoft/mana/mana_en.c
include/net/mana/mana.h
tools/hv/hv_kvp_daemon.c

HyperScaler Requested patches from Upstream
```
[jmaple@devbox code]$ egrep -B 5 -A 5 "\[TIMER\]|^Starting Build" kbuild.{jmaple}_mana_tools.resf_kernel-5.14.0-570.19.1.el9_6.log
CONFIG_LOCALVERSION="-_jmaple__mana_tools-3590a63a6e3c"
--
HOSTCC  scripts/kconfig/util.o
#
#
Starting Build
SYSHDR  arch/x86/include/generated/uapi/asm/unistd_32.h
SYSHDR  arch/x86/include/generated/uapi/asm/unistd_64.h
SYSHDR  arch/x86/include/generated/uapi/asm/unistd_x32.h
SYSHDR …
```

[SIG CLOUD 9] Net: Mana and hv_kvp_daemon logs

---

net/sched/sch_red.c

```
jira VULN-66500
cve CVE-2022-49921
commit-author Dan Carpenter <dan.carpenter@oracle.com> commit 8bdc2acd420c6f3dd1f1c78750ec989f02a1e2b9
We can't use "skb" again after passing it to qdisc_enqueue().  This is basically identical to commit 2f09707d0c97 ("sch_sfb: Also store skb len before calling child enqueue").
Fixes: d7f4f332f082 ("sch_red: update backlog as well")
Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 8bdc2acd420c6f3dd1f1c78750ec989f02a1e2b9)
```
```
/home/anmol/kernel-src-tree
CLEAN    resolve_btfids
CLEAN   scripts/basic
CLEAN   scripts/kconfig
CLEAN   include/config include/generated …
```

[fipslegacy-8.6] net: sched: Fix use after free in red_enqueue()

---

crypto/essiv.c

Fix a FIPS bug that got into the FIPS 9.2 code by mistake. This *only* affects the 9.2 FIPS kernel, no other kernel.
A bug was introduced while updating the kernel per atsec’s request. When key zeroization was added, setting the crypto algorithm key was removed in error. This re-adds the code to set the crypto key.
We can only fix this in compliant, as it touches the crypto code that is frozen in certified.
See this ticket for details:
https://ciqinc.atlassian.net/browse/LE-3197
Tested under non-FIPS and FIPS mode. NB. This bug only causes the algorithm to be unusable and an error message returned to users. No corruption or insecure algorithm use is allowed.

Partial revert of "In essiv_aead_setkey(), use the same logic as crypto_authenc_esn_setkey() to zeroize keys on exit."

---

drivers/net/netdevsim/dev.c

[LTS 8.6]
CVE-2022-49803
VULN-65787
<https://www.cve.org/CVERecord?id=CVE-2022-49803>
> In the Linux kernel, the following vulnerability has been resolved
>
>  netdevsim: Fix memory leak of nsim\_dev->fa\_cookie
>
>  kmemleak reports this issue:
>
>  unreferenced object 0xffff8881bac872d0 (size 8):
>    comm "sh", pid 58603, jiffies 4481524462 (age 68.065s)
>    hex dump (first 8 bytes):
>      04 00 00 00 de ad be ef                          &#x2026;&#x2026;..
>    backtrace:
>      [<00000000c80b8577>] \_\_kmalloc+0x49/0x150
>      [<000000005292b8c6>] nsim\_dev\_trap\_fa\_cookie\_write+0xc1/0x210 [netdevsim]
>      [<0000000093d78e77>] full\_proxy\_write+0xf3/0x180
>      [<000000005a662c16>] vfs\_write+0x1c5/0xaf0
>      [<000000007aabf84a>] ksys\_write+0xed/0x1c0
> …

[LTS 8.6] netdevsim: Fix memory leak of nsim_dev->fa_cookie

---

drivers/net/netdevsim/dev.c

jira VULN-65794
cve CVE-2022-49803
```
commit-author Wang Yufen <wangyufen@huawei.com>
commit 064bc7312bd09a48798418663090be0c776183db
kmemleak reports this issue:
unreferenced object 0xffff8881bac872d0 (size 8):
comm "sh", pid 58603, jiffies 4481524462 (age 68.065s)
hex dump (first 8 bytes):
04 00 00 00 de ad be ef                          ........
backtrace:
[<00000000c80b8577>] __kmalloc+0x49/0x150
[<000000005292b8c6>] nsim_dev_trap_fa_cookie_write+0xc1/0x210 [netdevsim]
[<0000000093d78e77>] full_proxy_write+0xf3/0x180
[<000000005a662c16>] vfs_write+0x1c5/0xaf0
[<000000007aabf84a>] ksys_write+0xed/0x1c0
[<000000005f1d2e47>] do_syscall_64+0x3b/0x90
[<000000006001c6ec>] entry_SYSCALL_64_after_hwframe+0x63/0xcd
The issue occurs in the following scenarios:
nsim_dev_trap_fa_cookie_write() …
```

[fips-9] netdevsim: Fix memory leak of nsim_dev->fa_cookie

---

drivers/net/netdevsim/dev.c

jira VULN-65791
cve CVE-2022-49803
```
commit-author Wang Yufen <wangyufen@huawei.com>
commit 064bc7312bd09a48798418663090be0c776183db
upstream-diff Minor conflicts because this kernel uses devlink_resources_unregister
instead of devl_resources_unregister and because this kernel
doesn't call devl_unlock(devlink).
kmemleak reports this issue:
unreferenced object 0xffff8881bac872d0 (size 8):
comm "sh", pid 58603, jiffies 4481524462 (age 68.065s)
hex dump (first 8 bytes):
04 00 00 00 de ad be ef                          ........
backtrace:
[<00000000c80b8577>] __kmalloc+0x49/0x150
[<000000005292b8c6>] nsim_dev_trap_fa_cookie_write+0xc1/0x210 [netdevsim]
[<0000000093d78e77>] full_proxy_write+0xf3/0x180
[<000000005a662c16>] vfs_write+0x1c5/0xaf0
[<000000007aabf84a>] ksys_write+0xed/0x1c0 …
```

[fips-legacy-8] netdevsim: Fix memory leak of nsim_dev->fa_cookie

---

drivers/net/ethernet/microsoft/mana/mana_en.c
include/net/mana/mana.h
tools/hv/hv_kvp_daemon.c
tools/testing/selftests/mm/hmm-tests.c

* Create `sig-cloud-9/5.14.0-570.X.1.el8_10` branch
None
```
[jmaple@devbox code]$ cat rolling.release.log
[rolling release update] Checking out branch:  sig-cloud-9/5.14.0-570.19.1.el9_6
b'b94108159618 (tag: resf_kernel-5.14.0-570.19.1.el9_6) Rebuild rocky9_6 with kernel-5.14.0-570.19.1.el9_6'
b'e8b954c95fef (tag: resf_kernel-5.14.0-570.18.1.el9_6, origin/fips-9-compliant/5.14.0-570.18.1.el9_6) Rebuild rocky9_6 …
```

[SIG-CLOUD-9] rebase custom changes to 5.14.0-570.22.1.el9 6

---

tools/testing/selftests/breakpoints/breakpoint_test_arm64.c

[LTS 8.6]
This commit fixes the problem with the compilation of `breakpoints:breakpoint_test_arm64` test on `aarch64` architecture.
The situation is exactly the same as in <https://github.com/ctrliq/kernel-src-tree/pull/330> (The `ciqlts8_6` and `ciqlts8_8` have the same history for the files in `tools/testing/selftests/breakpoints`. Also the same issue with `TRAP_HWBKPT` as in `ciqlts8_8`). See also associated <https://github.com/ctrliq/kernel-src-tree/pull/336>.

[LTS 8.6] selftests: breakpoints: Fix a typo of function name

---

net/sched/sch_red.c

```
jira VULN-66495
cve CVE-2022-49921
commit-author Dan Carpenter <dan.carpenter@oracle.com> commit 8bdc2acd420c6f3dd1f1c78750ec989f02a1e2b9
We can't use "skb" again after passing it to qdisc_enqueue().  This is basically identical to commit 2f09707d0c97 ("sch_sfb: Also store skb len before calling child enqueue").
Fixes: d7f4f332f082 ("sch_red: update backlog as well")
Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 8bdc2acd420c6f3dd1f1c78750ec989f02a1e2b9)
```
```
/home/anmol/kernel-src-tree …
```

[CBR 7.9] net: sched: Fix use after free in red_enqueue()

---

net/bluetooth/l2cap_core.c

```
jira VULN-66478
cve CVE-2022-49910
commit-author Maxim Mikityanskiy <maxtram95@gmail.com> commit 3aff8aaca4e36dc8b17eaa011684881a80238966
Fix the race condition between the following two flows that run in parallel:
1. l2cap_reassemble_sdu -> chan->ops->recv (l2cap_sock_recv_cb) -> __sock_queue_rcv_skb.
2. bt_sock_recvmsg -> skb_recv_datagram, skb_free_datagram.
An SKB can be queued by the first flow and immediately dequeued and freed by the second flow, therefore the callers of l2cap_reassemble_sdu can't use the SKB after that function returns. However, some places continue accessing struct l2cap_ctrl that resides in the SKB's CB for a short time after l2cap_reassemble_sdu returns, leading to a use-after-free condition (the stack trace is below, line numbers for kernel 5.19.8).
Fix it …
```

[fipslegacy-8.6] Bluetooth: L2CAP: Fix use-after-free caused by l2cap_reassemble_sdu

---

drivers/net/phy/mdio_bus.c

[LTS 8.6]
CVE-2022-49907
VULN-66411
<https://www.cve.org/CVERecord?id=CVE-2022-49907>
In the Linux kernel, the following vulnerability has been resolved:
net: mdio: fix undefined behavior in bit shift for __mdiobus_register
Shifting signed 32-bit value by 31 bits is undefined, so changing
significant bit to unsigned. The UBSAN warning calltrace like below:
UBSAN: shift-out-of-bounds in drivers/net/phy/mdio_bus.c:586:27
left shift of 1 by 31 places cannot be represented in type 'int'
Call Trace:
<TASK>
dump_stack_lvl+0x7d/0xa5
dump_stack+0x15/0x1b
ubsan_epilogue+0xe/0x4e
__ubsan_handle_shift_out_of_bounds+0x1e7/0x20c
__mdiobus_register+0x49d/0x4e0
fixed_mdio_bus_init+0xd8/0x12d
do_one_initcall+0x76/0x430
kernel_init_freeable+0x3b3/0x422
kernel_init+0x24/0x1e0
ret_from_fork+0x1f/0x30 …

[LTS 8.6] net: mdio: fix undefined behavior in bit shift for __mdiobus_register

---

drivers/net/ethernet/aquantia/atlantic/aq_nic.c

```
jira VULN-69384
cve CVE-2022-50066
commit-author Chia-Lin Kao (AceLan) <acelan.kao@canonical.com> commit 2ba5e47fb75fbb8fab45f5c1bc8d5c33d8834bd3
The final update statement of the for loop exceeds the array range, the dereference of self->aq_vec[i] is not checked and then leads to the index out of range error.
Also fixed this kind of coding style in other for loop.
[   97.937604] UBSAN: array-index-out-of-bounds in drivers/net/ethernet/aquantia/atlantic/aq_nic.c:1404:48
[   97.937607] index 8 is out of range for type 'aq_vec_s *[8]'
[   97.937608] CPU: 38 PID: 3767 Comm: kworker/u256:18 Not tainted 5.19.0+ #2
[   97.937610] Hardware name: Dell Inc. Precision 7865 Tower/, BIOS 1.0.0 06/12/2022
[   97.937611] Workqueue: events_unbound async_run_entry_fn
[   97.937616] Call Trace:
[ …
```

[LTS 86] net: atlantic: fix aq_vec index out of range error

---

fs/udf/namei.c

jira VULN-66096
cve CVE-2022-49846
```
commit-author ZhangPeng <zhangpeng362@huawei.com>
commit c8af247de385ce49afabc3bf1cf4fd455c94bfe8
Syzbot reported a slab-out-of-bounds Write bug:
loop0: detected capacity change from 0 to 2048
================================================================== BUG: KASAN: slab-out-of-bounds in udf_find_entry+0x8a5/0x14f0 fs/udf/namei.c:253
Write of size 105 at addr ffff8880123ff896 by task syz-executor323/3610
CPU: 0 PID: 3610 Comm: syz-executor323 Not tainted 6.1.0-rc2-syzkaller-00105-gb229b6ca5abb #0
Hardware name: Google Compute Engine/Google Compute Engine, BIOS Google 10/11/2022
Call Trace:
<TASK>
__dump_stack lib/dump_stack.c:88 [inline]
dump_stack_lvl+0x1b1/0x28e lib/dump_stack.c:106
print_address_description+0x74/0x340 mm/kasan/report.c:284 …
```

[fips-legacy-8] udf: Fix a slab-out-of-bounds write bug in udf_find_entry()

---

fs/udf/namei.c

jira VULN-66097
cve CVE-2022-49846
```
commit-author ZhangPeng <zhangpeng362@huawei.com>
commit c8af247de385ce49afabc3bf1cf4fd455c94bfe8
Syzbot reported a slab-out-of-bounds Write bug:
loop0: detected capacity change from 0 to 2048
================================================================== BUG: KASAN: slab-out-of-bounds in udf_find_entry+0x8a5/0x14f0 fs/udf/namei.c:253
Write of size 105 at addr ffff8880123ff896 by task syz-executor323/3610
CPU: 0 PID: 3610 Comm: syz-executor323 Not tainted 6.1.0-rc2-syzkaller-00105-gb229b6ca5abb #0
Hardware name: Google Compute Engine/Google Compute Engine, BIOS Google 10/11/2022
Call Trace:
<TASK>
__dump_stack lib/dump_stack.c:88 [inline]
dump_stack_lvl+0x1b1/0x28e lib/dump_stack.c:106
print_address_description+0x74/0x340 mm/kasan/report.c:284 …
```

[lts92] udf: Fix a slab-out-of-bounds write bug in udf_find_entry()

---

fs/udf/namei.c

jira VULN-66098
cve CVE-2022-49846
```
commit-author ZhangPeng <zhangpeng362@huawei.com>
commit c8af247de385ce49afabc3bf1cf4fd455c94bfe8
Syzbot reported a slab-out-of-bounds Write bug:
loop0: detected capacity change from 0 to 2048
================================================================== BUG: KASAN: slab-out-of-bounds in udf_find_entry+0x8a5/0x14f0 fs/udf/namei.c:253
Write of size 105 at addr ffff8880123ff896 by task syz-executor323/3610
CPU: 0 PID: 3610 Comm: syz-executor323 Not tainted 6.1.0-rc2-syzkaller-00105-gb229b6ca5abb #0
Hardware name: Google Compute Engine/Google Compute Engine, BIOS Google 10/11/2022
Call Trace:
<TASK>
__dump_stack lib/dump_stack.c:88 [inline]
dump_stack_lvl+0x1b1/0x28e lib/dump_stack.c:106
print_address_description+0x74/0x340 mm/kasan/report.c:284 …
```

[ciqlts9-4] udf: Fix a slab-out-of-bounds write bug in udf_find_entry()

---

drivers/net/ethernet/aquantia/atlantic/aq_nic.c

```
jira VULN-69388
cve CVE-2022-50066
commit-author Chia-Lin Kao (AceLan) <acelan.kao@canonical.com> commit 2ba5e47fb75fbb8fab45f5c1bc8d5c33d8834bd3
The final update statement of the for loop exceeds the array range, the dereference of self->aq_vec[i] is not checked and then leads to the index out of range error.
Also fixed this kind of coding style in other for loop.
[   97.937604] UBSAN: array-index-out-of-bounds in drivers/net/ethernet/aquantia/atlantic/aq_nic.c:1404:48
[   97.937607] index 8 is out of range for type 'aq_vec_s *[8]'
[   97.937608] CPU: 38 PID: 3767 Comm: kworker/u256:18 Not tainted 5.19.0+ #2
[   97.937610] Hardware name: Dell Inc. Precision 7865 Tower/, BIOS 1.0.0 06/12/2022
[   97.937611] Workqueue: events_unbound async_run_entry_fn
[   97.937616] Call Trace:
[ …
```

[fipslegacy-8.6] net: atlantic: fix aq_vec index out of range error

---

crypto/Kconfig
crypto/aead.c
crypto/cipher.c
crypto/drbg.c
crypto/ecdh.c
crypto/essiv.c
crypto/jitterentropy-kcapi.c
crypto/jitterentropy.c
crypto/jitterentropy.h
crypto/rng.c
include/linux/mm.h
lib/mpi/ec.c
mm/gup.c

This adds the missing baseline FIPS changes ported over by @jallisonciq, in addition to my new FIPS RNG performance overhaul.

Pick required FIPS changes + Add FIPS RNG performance overhaul

---

net/tipc/msg.c

jira VULN-8961
cve CVE-2024-36886
```
commit-author Paolo Abeni <pabeni@redhat.com>
commit 080cbb890286cd794f1ee788bbc5463e2deb7c2b
Sam Page (sam4k) working with Trend Micro Zero Day Initiative reported a UAF in the tipc_buf_append() error path:
BUG: KASAN: slab-use-after-free in kfree_skb_list_reason+0x47e/0x4c0 linux/net/core/skbuff.c:1183
Read of size 8 at addr ffff88804d2a7c80 by task poc/8034
CPU: 1 PID: 8034 Comm: poc Not tainted 6.8.2 #1
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.16.0-debian-1.16.0-5 04/01/2014
Call Trace:
<IRQ>
__dump_stack linux/lib/dump_stack.c:88
dump_stack_lvl+0xd9/0x1b0 linux/lib/dump_stack.c:106
print_address_description linux/mm/kasan/report.c:377
print_report+0xc4/0x620 linux/mm/kasan/report.c:488
kasan_report+0xda/0x110 …
```

[fips-9.2] tipc: fix UAF in error path

---

drivers/net/phy/mdio_bus.c

[CBR 7.9]
CVE-2022-49907
VULN-66410
<https://www.cve.org/CVERecord?id=CVE-2022-49907>
In the Linux kernel, the following vulnerability has been resolved:
net: mdio: fix undefined behavior in bit shift for __mdiobus_register
Shifting signed 32-bit value by 31 bits is undefined, so changing
significant bit to unsigned. The UBSAN warning calltrace like below:
UBSAN: shift-out-of-bounds in drivers/net/phy/mdio_bus.c:586:27
left shift of 1 by 31 places cannot be represented in type 'int'
Call Trace:
<TASK>
dump_stack_lvl+0x7d/0xa5
dump_stack+0x15/0x1b
ubsan_epilogue+0xe/0x4e
__ubsan_handle_shift_out_of_bounds+0x1e7/0x20c
__mdiobus_register+0x49d/0x4e0
fixed_mdio_bus_init+0xd8/0x12d
do_one_initcall+0x76/0x430
kernel_init_freeable+0x3b3/0x422
kernel_init+0x24/0x1e0
ret_from_fork+0x1f/0x30 …

[LTS 7.9] net: mdio: fix undefined behavior in bit shift for __mdiobus_register

---

crypto/Kconfig
crypto/aead.c
crypto/cipher.c
crypto/drbg.c
crypto/ecdh.c
crypto/essiv.c
crypto/jitterentropy-kcapi.c
crypto/jitterentropy.c
crypto/jitterentropy.h
crypto/rng.c
include/linux/mm.h
lib/mpi/ec.c
mm/gup.c

* Create `fips-9-compliant/5.14.0-570.X.1.el8_10` branch
None
`[rolling release update] 0 of 48 commits have FIPS protected changes`
```
[rolling release update] Rolling Product:  fips-9-compliant
[rolling release update] Checking out branch:  fips-9-compliant/5.14.0-570.18.1.el9_6
b'e8b954c95fef (tag: resf_kernel-5.14.0-570.18.1.el9_6) Rebuild rocky9_6 with kernel-5.14.0-570.18.1.el9_6'
b'838cd1e8d046 (tag: resf_kernel-5.14.0-570.17.1.el9_6) Rebuild rocky9_6 with …
```

[fips-9-compliant] Rebase Custom changes to 5.14.0-570.23.1.el9_6

---

arch/x86/kernel/cpu/common.c

* Create `sig-cloud-8/4.18.0-553.53.1.el8_10` branch
None
```
[jmaple@devbox code]$ cat RR.553.58.log
[rolling release update] Checking out branch:  sig-cloud-8/4.18.0-553.56.1.el8_10
b'1ad2baf0efe1 (tag: resf_kernel-4.18.0-553.56.1.el8_10) Rebuild rocky8_10 with kernel-4.18.0-553.56.1.el8_10'
b'6f9106f46020 (tag: resf_kernel-4.18.0-553.54.1.el8_10, origin/rocky8_10_rebuild) Rebuild rocky8_10 with …
```

[SIG-CLOUD-8] Rebase custom chages to 4.18.0-553.58.1.el8_10

---

tools/testing/selftests/net/reuseaddr_conflict.c

[LTS 8.6]
This commit fixes bad formatting for the `net:reuseaddr_conflict` test, which prevents automated tools from extracting the test's status.
Before:
TAP version 13
1..1
After:
TAP version 13
1..1
ok 1 selftests: net: reuseaddr_conflict
That it's a proper place for the newline (and not in some script executing the `reuseaddr_conflict` binary, for example) see similar tests from the same collection, eg:
<https://github.com/ctrliq/kernel-src-tree/blob/499f93ab350df5f7b6ba75c9e6002e086ec53038/tools/testing/selftests/net/reuseport_addr_any.c#L270-L278>
<https://github.com/ctrliq/kernel-src-tree/blob/499f93ab350df5f7b6ba75c9e6002e086ec53038/tools/testing/selftests/net/reuseport_bpf.c#L639-L640>
Turned out there is already a 31974122cfdeaf56abc18d8ab740d580d9833e90 fix in the mainline …

[LTS 8.6] selftests: reuseaddr_conflict: add missing new line at the end of the output

---

drivers/net/ethernet/microsoft/mana/mana_en.c
include/net/mana/mana.h
tools/hv/hv_kvp_daemon.c
tools/testing/selftests/mm/hmm-tests.c

* Create `sig-cloud-9/5.14.0-570.X.1.el8_10` branch
Already in Base Branch
```
96794508804e8d69a557061700908bb1781d7ab7 github actions: Update Actions to deal with devel
```
```
[jmaple@devbox kernel-src-tree-tools]$ python3 rolling-release-update.py --repo ../kernel-src-tree/ --new-base-branch rocky9_6 --old-rolling-branch $(git -C ../kernel-src-tree branch --sort=-creatordate --all --list "*sig-cloud-9*" | sed 's/remotes\/origin\///g' | head -n1)
[rolling release …
```

[SIG-CLOUD-9] rebase custom changes to 5.14.0-570.25.1.el9

---

drivers/net/ethernet/aquantia/atlantic/aq_nic.c

```
jira VULN-71367
cve CVE-2022-50066
commit-author Chia-Lin Kao (AceLan) <acelan.kao@canonical.com> 
commit 2ba5e47fb75fbb8fab45f5c1bc8d5c33d8834bd3
upstream-diff There was a merge conflict due to the CentOS 7 tree being
old but it was minor.
The final update statement of the for loop exceeds the array range, the dereference of self->aq_vec[i] is not checked and then leads to the index out of range error. Also fixed this kind of coding style in other for loop.
[   97.937604] UBSAN: array-index-out-of-bounds in drivers/net/ethernet/aquantia/atlantic/aq_nic.c:1404:48
[   97.937607] index 8 is out of range for type 'aq_vec_s *[8]'
[   97.937608] CPU: 38 PID: 3767 Comm: kworker/u256:18 Not tainted 5.19.0+ #2
[   97.937610] Hardware name: Dell Inc. Precision 7865 Tower/, BIOS 1.0.0 …
```

[CBR 7.9] net: atlantic: fix aq_vec index out of range error

---

net/sunrpc/svc.c

```
jira VULN-71608
cve CVE-2025-38089
commit-author Jeff Layton <jlayton@kernel.org>
commit 94d10a4dba0bc482f2b01e39f06d5513d0f75742
upstream-diff The following commits cause merge conflicts since they are
not present in the fips-9-compliant/5.14.0-284.30.1 :-
6d037b15e439 ("SUNRPC: Remove the rpc_stat variable in svc_process_common()")
ab42f4d9a26f ("sunrpc: don't change ->sv_stats if it doesn't exist")
649a692e0f2b ("SUNRPC: Convert RPC Reply header encoding to use xdr_stream")
tianshuo han reported a remotely-triggerable crash if the client sends a kernel RPC server a specially crafted packet. If decoding the RPC reply fails in such a way that SVC_GARBAGE is returned without setting the rq_accept_statp pointer, then that pointer can be dereferenced and a value stored there.
If it's …
```

[fips-9-compliant] sunrpc: handle SVC_GARBAGE during svc auth processing as auth error

---

crypto/drbg.c

The default DRBG is the one that has the highest priority. The priority
is defined based on the order of the list drbg_cores[] where the highest
priority is given to the last entry by drbg_fill_array.
With this patch the default DRBG is switched from HMAC SHA256 to HMAC
SHA512 to support compliance with SP800-90B and SP800-90C (current
draft).
The user of the crypto API is completely unaffected by the change.
Signed-off-by: Stephan Mueller <smueller@chronox.de>
Acked-by: simo Sorce <simo@redhat.com>
Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
This changes the default DRBG back to HMAC SHA256 as more processors have hardware acceleration for this algorithm.
Approved by the lab.

Set standard drbg in FIPS to use HMAC SHA256 - revert previous change. Approved by lab.

---

arch/x86/kernel/cpu/common.c

* Create `sig-cloud-8/4.18.0-553.53.1.el8_10` branch
None
```
jmaple@devbox kernel-src-tree-tools]$ python3 rolling-release-update.py --repo ../kernel-src-tree/ --new-base-branch rocky8_10 --old-rolling-branch sig-cloud-8/4.18.0-553.58.1.el8_10
[rolling release update] Checking out branch:  sig-cloud-8/4.18.0-553.58.1.el8_10
b'2e416d167715 (tag: resf_kernel-4.18.0-553.58.1.el8_10) Rebuild rocky8_10 with …
```

[SIG-CLOUD-8] Rebase custom chages to 4.18.0-553.62.1.el8_10

---

drivers/dma/idxd/irq.c

```
jira VULN-47991
cve CVE-2024-40956
commit-author Li RongQing <lirongqing@baidu.com>
commit e3215deca4520773cd2b155bed164c12365149a7
Use list_for_each_entry_safe() to allow iterating through the list and deleting the entry in the iteration process. The descriptor is freed via idxd_desc_complete() and there's a slight chance may cause issue for the list iterator when the descriptor is reused by another thread without it being deleted from the list.
Fixes: 16e19e11228b ("dmaengine: idxd: Fix list corruption in description completion")
Signed-off-by: Li RongQing <lirongqing@baidu.com>
Reviewed-by: Dave Jiang <dave.jiang@intel.com>
Reviewed-by: Fenghua Yu <fenghua.yu@intel.com>
Link: https://lore.kernel.org/r/20240603012444.11902-1-lirongqing@baidu.com
Signed-off-by: Vinod Koul …
```

[FIPS 9.2] dmaengine: idxd: Fix possible Use-After-Free in irq_process_work_list

---

fs/ext4/move_extent.c

```
jira VULN-4781
cve CVE-2024-26704
commit-author Baokun Li <libaokun1@huawei.com>
commit 55583e899a5357308274601364741a83e78d6ac4
In ext4_move_extents(), moved_len is only updated when all moves are successfully executed, and only discards orig_inode and donor_inode preallocations when moved_len is not zero. When the loop fails to exit after successfully moving some extents, moved_len is not updated and remains at 0, so it does not discard the preallocations.
If the moved extents overlap with the preallocated extents, the overlapped extents are freed twice in ext4_mb_release_inode_pa() and ext4_process_freed_data() (as described in commit 94d7c16cbbbd ("ext4: Fix double-free of blocks with EXT4_IOC_MOVE_EXT")), and bb_free is incremented twice. Hence when trim is executed, a …
```

[LTS 9.2] ext4: fix double-free of blocks due to wrong extents moved_len

---

net/sched/sch_taprio.c

```
jira VULN-8620
cve CVE-2024-50126
commit-author Dmitry Antipov <dmantipov@yandex.ru> commit b22db8b8befe90b61c98626ca1a2fbb0505e9fe3
Fix possible use-after-free in 'taprio_dump()' by adding RCU read-side critical section there. Never seen on x86 but found on a KASAN-enabled arm64 system when investigating https://syzkaller.appspot.com/bug?extid=b65e0af58423fc8a73aa:
[T15862] BUG: KASAN: slab-use-after-free in taprio_dump+0xa0c/0xbb0 [T15862] Read of size 4 at addr ffff0000d4bb88f8 by task repro/15862 [T15862]
[T15862] CPU: 0 UID: 0 PID: 15862 Comm: repro Not tainted 6.11.0-rc1-00293-gdefaf1a2113a-dirty #2 [T15862] Hardware name: QEMU QEMU Virtual Machine, BIOS edk2-20240524-5.fc40 05/24/2024 [T15862] Call trace:
[T15862]  dump_backtrace+0x20c/0x220
[T15862]  show_stack+0x2c/0x40 …
```

[LTS 9.4] net: sched: use RCU read-side critical section in taprio_dump()

---

drivers/media/usb/dvb-usb/technisat-usb2.c

[CBR 7.9]
CVE-2019-15505
VULN-7734
<https://www.cve.org/CVERecord?id=CVE-2019-15505>
> drivers/media/usb/dvb-usb/technisat-usb2.c in the Linux kernel through 5.2.9 has an out-of-bounds read via crafted USB device traffic (which may be remote via usbip or usbredir).
More concrete info about the issue in the fixing commit 0c4df39e504bf925ab666132ac3c98d6cbbe380b:
media: technisat-usb2: break out of loop at end of buffer
Ensure we do not access the buffer beyond the end if no 0xff byte
is encountered.
The driver is enabled in `configs/kernel-3.10.0-x86_64.config`
<https://github.com/ctrliq/kernel-src-tree/blob/3f2bd2004e523fc739a71a72f44ae8b4eb86571f/configs/kernel-3.10.0-x86_64.config#L3808>
Moreover, the affected function `technisat_usb2_get_ir` from …

[CBR 7.9] media: technisat-usb2: break out of loop at end of buffer

---

fs/cifs/smb2pdu.c

[LTS 9.2]
CVE-2024-50151
VULN-8636
<https://access.redhat.com/security/cve/CVE-2024-50151>
> A flaw was found in the cifs module in the Linux kernel. When building SMB2\_IOCTL requests using encryption, either enforced by the server or using the 'seal' mount option, an out-of-bounds write can be triggered when the user passes an input buffer greater than 328 bytes, resulting in memory corruption and a kernel crash.
CIFS (Common Internet File System) is basically a different name for Microsoft's SMB (Server Message Block) protocol, allowing for sharing files and printers on the network. Functionality-wise CIFS is the same as more Linux-native NFS system. From the practical perspective, using the CIFS module boils down to mounting appropriately addressed remote "share" at a local directory …

[LTS 9.2] smb: client: fix OOBs when building SMB2_IOCTL request

---

drivers/i2c/i2c-core-base.c

```
jira VULN-33
Signed-off-by: Pratham Patel <ppatel@ciq.com>
```
```
/home/pratham/kernel/ppatel_ciqlts9_2
fatal: not a git repository: /home/pratham/my-git-repos/ciq/kernel/bare-kernel-src-tree.git/worktrees/ppatel_ciqlts9_2
CLEAN   arch/x86/crypto …
```

i2c: Fix a potential use after free

---

drivers/i2c/i2c-core-base.c

```
jira VULN-28
Signed-off-by: Pratham Patel <ppatel@ciq.com>
```
```
CLEAN   .
CLEAN   arch/x86/realmode/rm …
```

[LTS-8.6] i2c: Fix a potential use after free

---

drivers/i2c/i2c-core-base.c

```
jira VULN-59662
Signed-off-by: Pratham Patel <ppatel@ciq.com>
```
```
CLEAN   arch/x86/crypto
CLEAN …
```

[fips-9.2] i2c: Fix a potential use after free

---

drivers/i2c/i2c-core-base.c

```
jira VULN-59661
Signed-off-by: Pratham Patel <ppatel@ciq.com>
```
```
CLEAN   arch/x86/boot/compressed
CLEAN   arch/x86/boot
CLEAN   arch/x86/crypto
CLEAN …
```

[lts-9.2] i2c: Fix a potential use after free

---

drivers/i2c/i2c-core.c

```
jira VULN-1497
upstream-diff There was a merge conflict because the file
drivers/i2c/i2c-core.c was renamed to drivers/i2c/i2c-core-base.c in
91ed53491f4f ("i2c: rename core source file to allow refactorization").
Signed-off-by: Pratham Patel …
```

[CBR-79] i2c: Fix a potential use after free

---

drivers/net/ethernet/intel/igb/igb_main.c
net/can/bcm.c
net/tls/tls_sw.c

Related CVEs Commits since this is the 8.7 kernel we need to check versus 8.6 and 8.8.
* `CVE-2023-52922` 
* https://github.com/ctrliq/kernel-src-tree/pull/180
* https://github.com/ctrliq/kernel-src-tree/pull/189
* `CVE-2023-45871`
* https://github.com/ctrliq/kernel-src-tree/pull/296
* `CVE-2024-0646`
* https://github.com/ctrliq/kernel-src-tree/pull/318
* https://github.com/ctrliq/kernel-src-tree/pull/317
```
[jmaple@devbox code]$ egrep -B 5 -A 5 "\[TIMER\]|^Starting Build" $(ls -t kbuild* | head -n1)
CLEAN   scripts/selinux/genheaders
CLEAN   scripts/selinux/mdp
CLEAN   scripts
CLEAN   include/config usr/include include/generated arch/x86/include/generated
CLEAN   .config .config.old .version Module.symvers
[TIMER]{MRPROPER}: 9s …
```

[FIPS Legacy 8] CVES: CVE-2023-52922,  CVE-2023-45871, CVE-2024-0646

---

fs/smb/client/smb2pdu.c

[LTS 9.4]
CVE-2024-50151
VULN-8637
<https://access.redhat.com/security/cve/CVE-2024-50151>
> A flaw was found in the cifs module in the Linux kernel. When building SMB2\_IOCTL requests using encryption, either enforced by the server or using the 'seal' mount option, an out-of-bounds write can be triggered when the user passes an input buffer greater than 328 bytes, resulting in memory corruption and a kernel crash.
See "Background" section in <https://github.com/ctrliq/kernel-src-tree/pull/431>.
(Situation differs slightly from <https://github.com/ctrliq/kernel-src-tree/pull/431> - the CIFS module files are already moved to `fs/smb/client/` dir in `ciqlts9_4`)
The original mainline fix is contained in 1ab60323c5201bef25f2a3dc0ccc404d9aca77f1. The affected file is …

[LTS 9.4] smb: client: fix OOBs when building SMB2_IOCTL request

---

fs/ceph/snap.c

```
jira VULN-65927
cve CVE-2022-49770
commit-author Xiubo Li <xiubli@redhat.com>
commit 51884d153f7ec85e18d607b2467820a90e0f4359
upstream-diff Absence of the following commit caused a merge conflict:
2e586641c950 ("ceph: do not update snapshot context when there is no new snapshot")
When decoding the snaps fails it maybe leaving the 'first_realm' and 'realm' pointing to the same snaprealm memory. And then it'll put it twice and could cause random use-after-free, BUG_ON, etc issues.
Link: https://tracker.ceph.com/issues/57686
Signed-off-by: Xiubo Li <xiubli@redhat.com>
Reviewed-by: Ilya Dryomov <idryomov@gmail.com>
Signed-off-by: Ilya Dryomov <idryomov@gmail.com>
(cherry picked from commit 51884d153f7ec85e18d607b2467820a90e0f4359)
Signed-off-by: Pratham Patel …
```

[cbr-79] ceph: avoid putting the realm twice when decoding snaps fails

---

net/netfilter/nf_tables_api.c

```
jira VULN-6585
cve CVE-2023-3777
commit-author Pablo Neira Ayuso <pablo@netfilter.org> commit 6eaf41e87a223ae6f8e7a28d6e78384ad7e407f8
Skip bound chain when flushing table rules, the rule that owns this chain releases these objects.
Otherwise, the following warning is triggered:
WARNING: CPU: 2 PID: 1217 at net/netfilter/nf_tables_api.c:2013 nf_tables_chain_destroy+0x1f7/0x210 [nf_tables]
CPU: 2 PID: 1217 Comm: chain-flush Not tainted 6.1.39 #1
RIP: 0010:nf_tables_chain_destroy+0x1f7/0x210 [nf_tables]
Fixes: d0e2c7de92c7 ("netfilter: nf_tables: add NFT_CHAIN_BINDING")
Reported-by: Kevin Rich <kevinrich1337@gmail.com>
(cherry picked from commit 6eaf41e87a223ae6f8e7a28d6e78384ad7e407f8) …
```

[LTS 9.2]netfilter: nf_tables: skip bound chain on rule flush

---

net/bluetooth/hci_conn.c
net/bluetooth/hci_sysfs.c

```
jira VULN-334
cve CVE-2023-28464
commit-author ZhengHan Wang <wzhmmmmm@gmail.com>
commit a85fb91e3d728bdfc80833167e8162cce8bc7004
syzbot reports a slab use-after-free in hci_conn_hash_flush [1]. After releasing an object using hci_conn_del_sysfs in the hci_conn_cleanup function, releasing the same object again using the hci_dev_put and hci_conn_put functions causes a double free. Here's a simplified flow:
hci_conn_del_sysfs:
hci_dev_put
put_device
kobject_put
kref_put
kobject_release
kobject_cleanup
kfree_const
kfree(name)
hci_dev_put:
...
kfree(name)
hci_conn_put:
put_device
...
kfree(name)
This patch drop the hci_dev_put and hci_conn_put function call in hci_conn_cleanup function, because the object is freed in hci_conn_del_sysfs function.
This patch also fixes the refcounting in …
```

[LTS 92] Bluetooth: Fix double free in hci_conn_cleanup

---

include/linux/perf_event.h
kernel/events/core.c

```
jira VULN-6760
pre-cve CVE-2023-5717
commit-author Peter Zijlstra <peterz@infradead.org>
commit 32671e3799ca2e4590773fd0e63aaa4229e50c06
Because group consistency is non-atomic between parent (filedesc) and children
(inherited) events, it is possible for PERF_FORMAT_GROUP read() to try and sum
non-matching counter groups -- with non-sensical results.
Add group_generation to distinguish the case where a parent group removes and
adds an event and thus has the same number, but a different configuration of
events as inherited groups.
This became a problem when commit fa8c269353d5 ("perf/core: Invert
perf_read_group() loops") flipped the order of child_list and sibling_list.
Previously it would iterate the group (sibling_list) first, and for each
sibling traverse the child_list. In this …
```

[LTS 9.2] perf: Disallow mis-matched inherited group reads

---

net/netfilter/nf_tables_api.c

```
jira VULN-8826
cve CVE-2023-3777
commit-author Pablo Neira Ayuso <pablo@netfilter.org> commit 6eaf41e87a223ae6f8e7a28d6e78384ad7e407f8
Skip bound chain when flushing table rules, the rule that owns this chain releases these objects.
Otherwise, the following warning is triggered:
WARNING: CPU: 2 PID: 1217 at net/netfilter/nf_tables_api.c:2013 nf_tables_chain_destroy+0x1f7/0x210 [nf_tables]
CPU: 2 PID: 1217 Comm: chain-flush Not tainted 6.1.39 #1
RIP: 0010:nf_tables_chain_destroy+0x1f7/0x210 [nf_tables]
Fixes: d0e2c7de92c7 ("netfilter: nf_tables: add NFT_CHAIN_BINDING")
Reported-by: Kevin Rich <kevinrich1337@gmail.com>
(cherry picked from commit 6eaf41e87a223ae6f8e7a28d6e78384ad7e407f8) …
```

[fips 9.2] netfilter: nf_tables: skip bound chain on rule flush

---

arch/arm64/kvm/vgic/vgic-its.c

[LTS 9.2]
CVE-2024-26598
VULN-8190
<https://access.redhat.com/security/cve/CVE-2024-26598>
> A flaw was found in the Linux kernel pertaining to a potential use-after-free (UAF) scenario in a system involving Logical Partitioning Interrupts (LPI) translation cache operations. Specifically, the issue arises when a cache hit occurs concurrently with an operation that invalidates the cache, such as a DISCARD ITS command. The root cause is traced to vgic\_its\_check\_cache() not appropriately managing the reference count of the vgic\_irq object. Upon returning from this function, the reference count of vgic\_irq is not incremented. This issue can lead to the object being prematurely freed while still in use by other parts of the system, potentially resulting in undefined behavior or system …

[LTS 9.2] KVM: arm64: vgic-its: Avoid potential UAF in LPI translation cache

---

net/tipc/crypto.c

jira VULN-70867
cve CVE-2025-38052
```
commit-author Wang Liang <wangliang74@huawei.com>
commit e279024617134c94fd3e37470156534d5f2b3472
Syzbot reported a slab-use-after-free with the following call trace:
==================================================================
BUG: KASAN: slab-use-after-free in tipc_aead_encrypt_done+0x4bd/0x510 net/tipc/crypto.c:840
Read of size 8 at addr ffff88807a733000 by task kworker/1:0/25
Call Trace:
kasan_report+0xd9/0x110 mm/kasan/report.c:601
tipc_aead_encrypt_done+0x4bd/0x510 net/tipc/crypto.c:840
crypto_request_complete include/crypto/algapi.h:266
aead_request_complete include/crypto/internal/aead.h:85
cryptd_aead_crypt+0x3b8/0x750 crypto/cryptd.c:772
crypto_request_complete include/crypto/algapi.h:266
cryptd_queue_worker+0x131/0x200 …
```

[fips-legacy-8] net/tipc: fix slab-use-after-free Read in tipc_aead_encrypt_done

---

include/linux/perf_event.h
kernel/events/core.c

```
jira VULN-8890
cve CVE-2023-5717
commit-author Peter Zijlstra <peterz@infradead.org>
commit https://github.com/ctrliq/kernel-src-tree/commit/32671e3799ca2e4590773fd0e63aaa4229e50c06
upstream-diff This patch causes kABI breakage due to a change in the
struct perf_event layout after adding the group_generation field.
Hence, to preserve kABI compatibility, use RH_KABI_EXTEND macro
to safely append the new field without affecting the existing layout.
Because group consistency is non-atomic between parent (filedesc) and children
(inherited) events, it is possible for PERF_FORMAT_GROUP read() to try and sum
non-matching counter groups -- with non-sensical results.
Add group_generation to distinguish the case where a parent group removes and
adds an event and thus has the same number, but a …
```

[fips-legacy-8] perf: Disallow mis-matched inherited group reads

---

net/ipv4/af_inet.c

```
jira VULN-41186
cve CVE-2024-56601
commit-author Ignat Korchagin <ignat@cloudflare.com> commit 9365fa510c6f82e3aa550a09d0c5c6b44dbc78ff
sock_init_data() attaches the allocated sk object to the provided sock object. If inet_create() fails later, the sk object is freed, but the sock object retains the dangling pointer, which may create use-after-free later.
Clear the sk pointer in the sock object on error.
Signed-off-by: Ignat Korchagin <ignat@cloudflare.com>
Reviewed-by: Kuniyuki Iwashima <kuniyu@amazon.com>
Link: https://patch.msgid.link/20241014153808.51894-7-ignat@cloudflare.com
Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 9365fa510c6f82e3aa550a09d0c5c6b44dbc78ff) …
```

[LTS 9.4] net: inet: do not leave a dangling sk pointer in inet_create()

---

drivers/iommu/iommu.c
drivers/md/dm-ioctl.c
drivers/net/wireless/mediatek/mt76/mac80211.c
drivers/net/wireless/mediatek/mt76/mt76.h
drivers/net/wireless/mediatek/mt76/mt7603/main.c
drivers/net/wireless/mediatek/mt76/mt7615/main.c
drivers/net/wireless/mediatek/mt76/mt76x02_util.c
drivers/net/wireless/mediatek/mt76/mt7915/main.c
drivers/net/wireless/mediatek/mt76/mt7921/main.c
drivers/net/wireless/mediatek/mt76/tx.c
drivers/scsi/libfc/fc_exch.c
fs/ext4/xattr.c
net/atm/lec.c
net/tipc/core.c

```
Running make mrproper...
CLEAN   .
CLEAN   arch/x86/realmode/rm
CLEAN   arch/x86/lib
CLEAN   certs
CLEAN   drivers/firmware/efi/libstub
CLEAN   drivers/gpu/drm/radeon
CLEAN   drivers/scsi
CLEAN   drivers/tty/vt
CLEAN   drivers/video/logo
CLEAN   kernel/debug/kdb
CLEAN   kernel
CLEAN   lib/raid6
CLEAN   lib
CLEAN   net/wireless
CLEAN   security/selinux
CLEAN   usr
CLEAN   arch/x86/boot/compressed
CLEAN   arch/x86/boot
CLEAN   arch/x86/tools
CLEAN    resolve_btfids
CLEAN   .tmp_versions
CLEAN   scripts/basic
CLEAN   scripts/genksyms
CLEAN   scripts/kconfig
CLEAN   scripts/mod
CLEAN   scripts/selinux/genheaders
CLEAN   scripts/selinux/mdp
CLEAN …
```

[LTS-8.6] CVE-2022-49114 CVE-2022-49328 CVE-2025-22004 CVE-2022-49696 CVE-2025-37738 CVE-2022-49122 CVE-2022-48796

---

.github/workflows/upstream-commit-check.yml

LE-3204
This github action checks the PR commits for references to upstream linux commits (lines starting with "commit <hash>") and does two things:
1.  Checks that this hash exists in the upstream linux kernel history
2.  Checks if there are any Fixes: references for the referenced commit in the upstream linux kernel history
If either of those are found to be true a comment is added to the PR with the pertinent information.
The logic for the check is provided by the check_upstream_commits.py script from kernel-src-tree-tools
See the comment below for an example of what an automated message from this commit checker will look like:
https://github.com/ctrliq/kernel-src-tree/pull/323#issuecomment-3168916907

[cbr79] github actions: Add upstream commit checker

---

net/ipv4/af_inet.c

```
jira VULN-41185
cve CVE-2024-56601
commit-author Ignat Korchagin <ignat@cloudflare.com> commit 9365fa510c6f82e3aa550a09d0c5c6b44dbc78ff
sock_init_data() attaches the allocated sk object to the provided sock object. If inet_create() fails later, the sk object is freed, but the sock object retains the dangling pointer, which may create use-after-free later.
Clear the sk pointer in the sock object on error.
Signed-off-by: Ignat Korchagin <ignat@cloudflare.com>
Reviewed-by: Kuniyuki Iwashima <kuniyu@amazon.com>
Link: https://patch.msgid.link/20241014153808.51894-7-ignat@cloudflare.com
Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 9365fa510c6f82e3aa550a09d0c5c6b44dbc78ff) …
```

[LTS 9.2] net: inet: do not leave a dangling sk pointer in inet_create()

---

include/linux/perf_event.h
kernel/events/core.c

```
jira VULN-8891
cve CVE-2023-5717
commit-author Peter Zijlstra <peterz@infradead.org>
commit https://github.com/ctrliq/kernel-src-tree/commit/32671e3799ca2e4590773fd0e63aaa4229e50c06
upstream-diff This patch causes kABI breakage due to a change in the
struct perf_event layout after adding the group_generation field.
Hence, to preserve kABI compatibility, use RH_KABI_EXTEND macro
to safely append the new field without affecting the existing layout.
Because group consistency is non-atomic between parent (filedesc) and children
(inherited) events, it is possible for PERF_FORMAT_GROUP read() to try and sum
non-matching counter groups -- with non-sensical results.
Add group_generation to distinguish the case where a parent group removes and
adds an event and thus has the same number, but a …
```

[fips-9-compliant] perf: Disallow mis-matched inherited group reads

---

net/ipv4/af_inet.c

```
jira VULN-41187
cve CVE-2024-56601
commit-author Ignat Korchagin <ignat@cloudflare.com> commit 9365fa510c6f82e3aa550a09d0c5c6b44dbc78ff
sock_init_data() attaches the allocated sk object to the provided sock object. If inet_create() fails later, the sk object is freed, but the sock object retains the dangling pointer, which may create use-after-free later.
Clear the sk pointer in the sock object on error.
Signed-off-by: Ignat Korchagin <ignat@cloudflare.com>
Reviewed-by: Kuniyuki Iwashima <kuniyu@amazon.com>
Link: https://patch.msgid.link/20241014153808.51894-7-ignat@cloudflare.com
Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 9365fa510c6f82e3aa550a09d0c5c6b44dbc78ff) …
```

[FIPS 9.2] net: inet: do not leave a dangling sk pointer in inet_create()

---

net/can/j1939/main.c

```
jira VULN-63435
cve CVE-2021-47459
commit-author Ziyang Xuan <william.xuanziyang@huawei.com> commit d9d52a3ebd284882f5562c88e55991add5d01586
It will trigger UAF for rx_kref of j1939_priv as following.
cpu0                                    cpu1
j1939_sk_bind(socket0, ndev0, ...)
j1939_netdev_start
j1939_sk_bind(socket1, ndev0, ...)
j1939_netdev_start
j1939_priv_set
j1939_priv_get_by_ndev_locked
j1939_jsk_add
.....
j1939_netdev_stop
kref_put_lock(&priv->rx_kref, ...)
kref_get(&priv->rx_kref, ...)
REFCOUNT_WARN("addition on 0;...")
==================================================== refcount_t: addition on 0; use-after-free.
WARNING: CPU: 1 PID: 20874 at lib/refcount.c:25 refcount_warn_saturate+0x169/0x1e0 RIP: 0010:refcount_warn_saturate+0x169/0x1e0
Call Trace: …
```

[LTS 9.2] can: j1939: j1939_netdev_start(): fix UAF for rx_kref of j1939_priv

---

.github/workflows/upstream-commit-check.yml

LE-3768
Same as https://github.com/ctrliq/kernel-src-tree/pull/474
This github action checks the PR commits for references to upstream linux commits (lines starting with "commit <hash>") and does two things:
1.  Checks that this hash exists in the upstream linux kernel history
2.  Checks if there are any Fixes: references for the referenced commit in the upstream linux kernel history
If either of those are found to be true a comment is added to the PR with the pertinent information.
The logic for the check is provided by the check_upstream_commits.py script from kernel-src-tree-tools

[lts92] github actions: Add upstream commit checker

---

.github/workflows/upstream-commit-check.yml

LE-3770
Same as https://github.com/ctrliq/kernel-src-tree/pull/474
This github action checks the PR commits for references to upstream linux commits (lines starting with "commit <hash>") and does two things:
1.  Checks that this hash exists in the upstream linux kernel history
2.  Checks if there are any Fixes: references for the referenced commit in the upstream linux kernel history
If either of those are found to be true a comment is added to the PR with the pertinent information.
The logic for the check is provided by the check_upstream_commits.py script from kernel-src-tree-tools

[fips-8] github actions: Add upstream commit checker

---

.github/workflows/upstream-commit-check.yml

LE-3772
Same as https://github.com/ctrliq/kernel-src-tree/pull/474
This github action checks the PR commits for references to upstream linux commits (lines starting with "commit <hash>") and does two things:
1.  Checks that this hash exists in the upstream linux kernel history
2.  Checks if there are any Fixes: references for the referenced commit in the upstream linux kernel history
If either of those are found to be true a comment is added to the PR with the pertinent information.
The logic for the check is provided by the check_upstream_commits.py script from kernel-src-tree-tools

[fips-legacy-8] github actions: Add upstream commit checker

---

drivers/net/ethernet/broadcom/bnxt/bnxt.c
drivers/uio/uio.c
fs/cifs/link.c
fs/userfaultfd.c
net/bluetooth/hci_event.c
net/ipv4/tcp_ipv4.c
net/ipv6/route.c
net/mptcp/pm_netlink.c

```
Running make mrproper...
CLEAN   .
CLEAN   arch/x86/realmode/rm
CLEAN   arch/x86/lib
CLEAN   certs
CLEAN   drivers/firmware/efi/libstub
CLEAN   drivers/gpu/drm/radeon
CLEAN   drivers/scsi
CLEAN   drivers/tty/vt
CLEAN   drivers/video/logo
CLEAN   kernel/debug/kdb
CLEAN   kernel
CLEAN   lib/raid6
CLEAN   lib
CLEAN   net/wireless
CLEAN   security/selinux
CLEAN   usr
CLEAN   arch/x86/boot/compressed
CLEAN   arch/x86/boot
CLEAN   arch/x86/tools
CLEAN    resolve_btfids
CLEAN   .tmp_versions
CLEAN   scripts/basic
CLEAN   scripts/genksyms
CLEAN   scripts/kconfig
CLEAN   scripts/mod
CLEAN   scripts/selinux/genheaders
CLEAN   scripts/selinux/mdp
CLEAN …
```

[LTS-8.6] CVE-2023-52439 CVE-2021-47461 CVE-2024-26852 CVE-2024-36904 CVE-2022-48637 CVE-2024-46858 CVE-2022-49058 CVE-2022-49111

---

net/sched/sch_hfsc.c

[LTS 8.6]
CVE-2025-37890
VULN-68290
<https://access.redhat.com/security/cve/CVE-2025-37890>
> A use-after-free vulnerability has been identified in the Linux kernel's HFSC (Hierarchical Fair Service Curve) queuing discipline when it is configured with NETEM (Network Emulation) as a child. This flaw can lead to a kernel panic or crash due to incorrect assumptions about the queue state. Exploitation of this vulnerability requires local access with CAP\_NET\_ADMIN privileges and control over the qdisc (queueing discipline) setup. A local attacker could leverage this flaw to achieve denial of service or escalate privileges. Given that it affects kernel memory structures, successful exploitation could result in memory corruption, data leaks, or arbitrary write capabilities, leading to a full …

[LTS 8.6] net_sched: hfsc: Address reentrant enqueue adding class to eltree twice

---

.github/workflows/build-check_aarch64.yml
.github/workflows/build-check_x86_64.yml

LE-3795
After the build check, perform a kabi check
Note: There are no -rt Module.kabi_* files.  So we are only checking the kabi for x86_64 and aarch64

[lts94] github actions: Add kabi checks

---

net/bluetooth/l2cap_sock.c

```
Bluetooth: L2CAP: Fix use-after-free in l2cap_sock_ready_cb
jira VULN-8836
cve CVE-2023-40283
commit-author Sungwoo Kim <iam@sung-woo.kim>
commit https://github.com/ctrliq/kernel-src-tree/commit/1728137b33c00d5a2b5110ed7aafb42e7c32e4a1
l2cap_sock_release(sk) frees sk. However, sk's children are still alive
and point to the already free'd sk's address.
To fix this, l2cap_sock_release(sk) also cleans sk's children.
==================================================================
BUG: KASAN: use-after-free in l2cap_sock_ready_cb+0xb7/0x100 net/bluetooth/l2cap_sock.c:1650
Read of size 8 at addr ffff888104617aa8 by task kworker/u3:0/276
CPU: 0 PID: 276 Comm: kworker/u3:0 Not tainted 6.2.0-00001-gef397bd4d5fb-dirty https://github.com/ctrliq/kernel-src-tree/pull/59
Hardware name: QEMU …
```

[fips-legacy-8] Bluetooth: L2CAP: Fix use-after-free in l2cap_sock_ready_cb

---

drivers/infiniband/hw/mana/main.c
drivers/net/ethernet/microsoft/Kconfig
drivers/net/ethernet/microsoft/mana/gdma_main.c
drivers/net/ethernet/microsoft/mana/hw_channel.c
drivers/net/ethernet/microsoft/mana/mana_en.c
drivers/net/ethernet/microsoft/mana/shm_channel.c
include/net/mana/gdma.h
include/net/mana/mana.h

```
RDMA/mana_ib: use the correct page table index based on hardware page size
jira LE-3812
commit-author Long Li <longli@microsoft.com>
commit 9e517a8
upstream-diff There were build failures and conflicts due to the
following missing commits :-
e849aad ("RDMA/mana_ib: Fix bug in creation of dma regions")
071bade ("net: mana: Add support for page sizes other than 4KB on ARM64")
5861cd1 ("net: mana: Enable MANA driver on ARM64 with 4K page size")
MANA hardware uses 4k page size. When calculating the page table index,
it should use the hardware page size, not the system page size.
Fixes: 0266a17 ("RDMA/mana_ib: Add a driver for Microsoft Azure Network Adapter")
Signed-off-by: Long Li <longli@microsoft.com>
Link: …
```

[LE-3812] RDMA/mana_ib: use the correct page table index based on hardware page size

---

drivers/i2c/busses/i2c-designware-master.c
net/tls/tls_strp.c

```
tls: always refresh the queue when reading sock
jira VULN-89195
cve CVE-2025-38471
commit-author Jakub Kicinski <kuba@kernel.org>
commit 4ab26bce3969f8fd925fe6f6f551e4d1a508c68b
```
```
i2c/designware: Fix an initialization issue
jira VULN-79510
cve CVE-2025-38380
commit-author Michael J. Ruhl <michael.j.ruhl@intel.com>
commit 3d30048958e0d43425f6d4e76565e6249fa71050
```
```
Running make mrproper...
[TIMER]{MRPROPER}: 10s
CONFIG_LOCALVERSION="-bmastbergen_ciqlts9_4_many-vulns-8-21-25-5c89329c35c9"
--
HOSTCC  scripts/kconfig/util.o
#
#
Starting Build
SYSHDR …
```

[lts94] CVE-2025-38380 and CVE-38471

---

drivers/net/ethernet/microsoft/mana/mana_en.c
include/net/mana/mana.h
tools/hv/hv_kvp_daemon.c

* Create `sig-cloud-10/6.12.0-55.X.1.el10_0` branch
None
```
[jmaple@devbox code]$ cat RR.resf_kernel-6.12.0-55.25.1.el10_0-23-g9c864bb5ae3f.log
[rolling release update] Rolling Product:  sig-cloud-10
[rolling release update] Checking out branch:  sig-cloud-10/6.12.0-55.21.1.el10_0
b'fef28841a44f (tag: resf_kernel-6.12.0-55.21.1.el10_0) Rebuild rocky10_0 with kernel-6.12.0-55.21.1.el10_0'
b'3381775694c1 (tag: resf_kernel-6.12.0-55.20.1.el10_0) Rebuild rocky10_0 with …
```

[SIG-CLOUD-10] Rebase custom changes to 6.12.0-55.27.1.el10_0

---

net/sched/sch_hfsc.c

[FIPS 8.10]
CVE-2025-37890
VULN-68293
VULN-68292
<https://access.redhat.com/security/cve/CVE-2025-37890>
> A use-after-free vulnerability has been identified in the Linux kernel's HFSC (Hierarchical Fair Service Curve) queuing discipline when it is configured with NETEM (Network Emulation) as a child. This flaw can lead to a kernel panic or crash due to incorrect assumptions about the queue state. Exploitation of this vulnerability requires local access with CAP\_NET\_ADMIN privileges and control over the qdisc (queueing discipline) setup. A local attacker could leverage this flaw to achieve denial of service or escalate privileges. Given that it affects kernel memory structures, successful exploitation could result in memory corruption, data leaks, or arbitrary write capabilities, …

[FIPS 8.10] net_sched: hfsc: Address reentrant enqueue adding class to eltree twice

---

arch/powerpc/lib/sstep.c
drivers/gpu/drm/amd/amdgpu/amdgpu_mes.c
drivers/gpu/drm/vmwgfx/vmwgfx_fence.c
drivers/memstick/host/rtsx_usb_ms.c
drivers/misc/vmw_vmci/vmci_queue_pair.c
drivers/tty/vt/vt_ioctl.c
fs/squashfs/squashfs_fs.h
fs/squashfs/squashfs_fs_sb.h
fs/squashfs/xattr.h
fs/squashfs/xattr_id.c

[LTS 9.4]
CVE-2025-22020  VULN-64887
CVE-2022-48804  VULN-8027
CVE-2022-49788  VULN-65841
CVE-2023-52606  VULN-8150
CVE-2023-52933  VULN-55076
CVE-2024-36960  VULN-8241
CVE-2024-38581  VULN-8245
2c7bbea35c96f130001235da05c2b613eda49118:
memstick: rtsx_usb_ms: Fix slab-use-after-free in rtsx_usb_ms_drv_remove
jira VULN-64887
cve CVE-2025-22020
commit-author Luo Qiu <luoqiu@kylinsec.com.cn>
commit 4676741a3464b300b486e70585c3c9b692be1632
9499e079cafe9f72418f74f0ecc28e71f1a61607:
vt_ioctl: fix array_index_nospec in vt_setactivate
jira VULN-8027
cve CVE-2022-48804
commit-author Jakob Koschel <jakobkoschel@gmail.com>
commit 61cc70d9e8ef5b042d4ed87994d20100ec8896d9
8bdcb877b9da5c4814a43ecf4fec975e862d3fa4:
misc/vmw_vmci: fix an infoleak in vmci_host_do_receive_datagram()
jira VULN-65841
cve …

[LTS 9.4] CVE-2025-22020, CVE-2022-48804, CVE-2022-49788, CVE-2023-52606, CVE-2023-52933, CVE-2024-36960, CVE-2024-38581

---

drivers/scsi/storvsc_drv.c

jira LE-3546
```
commit-author Dexuan Cui <decui@microsoft.com>
commit b2f966568faaad326de97481096d0f3dc0971c43
Currently storvsc_timeout is only used in storvsc_sdev_configure(), and 5s and 10s are used elsewhere. It turns out that rarely the 5s is not enough on Azure, so let's use storvsc_timeout everywhere.
In case a timeout happens and storvsc_channel_init() returns an error, close the VMBus channel so that any host-to-guest messages in the channel's ringbuffer, which might come late, can be safely ignored.
Add a "const" to storvsc_timeout.
Cc: stable@kernel.org
Signed-off-by: Dexuan Cui <decui@microsoft.com>
Link: https://lore.kernel.org/r/1749243459-10419-1-git-send-email-decui@microsoft.com
Reviewed-by: Long Li <longli@microsoft.com>
Signed-off-by: Martin K. Petersen …
```

[LE-3546] scsi: storvsc: Increase the timeouts to storvsc_timeout

---

drivers/hv/channel.c
drivers/net/hyperv/hyperv_net.h
drivers/net/hyperv/netvsc.c
drivers/net/hyperv/netvsc_drv.c
drivers/net/hyperv/rndis_filter.c
drivers/scsi/storvsc_drv.c
include/linux/hyperv.h

```
Drivers: hv: vmbus: Remove vmbus_sendpacket_pagebuffer()
jira LE-3554
commit-author Michael Kelley <mhklinux@outlook.com>
commit 45a442fe369e6c4e0b4aa9f63b31c3f2f9e2090e
With the netvsc driver changed to use vmbus_sendpacket_mpb_desc()
instead of vmbus_sendpacket_pagebuffer(), the latter has no remaining
callers. Remove it.
--------------------------------------------------------------------------------------------
hv_netvsc: Remove rmsg_pgcnt
jira LE-3554
commit-author Michael Kelley <mhklinux@outlook.com>
commit 5bbc644bbf4e97a05bc0cb052189004588ff8a09
init_page_array() now always creates a single page buffer array entry
for the rndis message, even if the rndis message crosses a page
boundary. As such, the number of page buffer array entries used for
the rndis message must no longer …
```

[SIG-CLOUD-9] [LE-3554] Drivers: hv: vmbus: Remove vmbus_sendpacket_pagebuffer()

---

drivers/net/ethernet/microsoft/mana/gdma_main.c
drivers/net/ethernet/microsoft/mana/hw_channel.c
drivers/net/ethernet/microsoft/mana/mana_en.c
drivers/net/hyperv/hyperv_net.h
drivers/net/hyperv/netvsc_drv.c
drivers/net/hyperv/rndis_filter.c

```
net: mana: Add debug logs in MANA network driver
jira LE-3889
commit-author Erni Sri Satya Vennela <ernis@linux.microsoft.com>
commit 47dfd7a72257e91171d56e220ea484a04df89847
Add more logs to assist in debugging and monitoring
driver behaviour, making it easier to identify potential
issues  during development and testing.
-----------------------------------------------------------------------------
net: mana: Allow tso_max_size to go up-to GSO_MAX_SIZE
jira LE-3885
commit-author Shradha Gupta <shradhagupta@linux.microsoft.com>
commit 27315836f4bcc8e4879d50dfc1fa6eb41e7952ef
Allow the max aggregated pkt size to go up-to GSO_MAX_SIZE for MANA NIC.
This patch only increases the max allowable gso/gro pkt size for MANA
devices and does not change the defaults.
Following are the perf …
```

[SIG-CLOUD-9]  LE-3885 and LE-3889

---

.github/workflows/upstream-commit-check.yml

The upstream commit check workflow was failing for pull requests originating from forked repositories. The previous implementation incorrectly assumed the pull request branch existed on the base repository.
This commit corrects the workflow to ensure the pull request branch is checked out from the correct source repository, while the base branch is fetched from the target repository.

[lts86] github actions: Fix upstream commit check for forks

---

.github/workflows/upstream-commit-check.yml

The upstream commit check workflow was failing for pull requests originating from forked repositories. The previous implementation incorrectly assumed the pull request branch existed on the base repository.
This commit corrects the workflow to ensure the pull request branch is checked out from the correct source repository, while the base branch is fetched from the target repository.

[fips-legacy-8] github actions: Fix upstream commit check for forks

---

drivers/media/usb/uvc/uvc_ctrl.c
drivers/media/usb/uvc/uvc_v4l2.c
drivers/media/usb/uvc/uvcvideo.h

[LTS 9.4]
CVE-2024-58002
VULN-53465
<https://access.redhat.com/security/cve/CVE-2024-58002>
> A dangling pointer vulnerability was found in the Linux kernel. When an async control is written, a copy of a pointer is made in the file handle that started the operation. If the user closes that file descriptor, its structure will be freed and there will be one dangling pointer per pending async control that the driver will try to use, leading to denial of service of the system.
The affected module is "USB Video Class", `uvcvideo.ko`. Enabled by `CONFIG_USB_VIDEO_CLASS`, set to `m` in all config files of `ciqlts9_4`:
$ grep 'USB_VIDEO_CLASS\b' configs/*.config
configs/kernel-aarch64-64k-debug-rhel.config:CONFIG_USB_VIDEO_CLASS=m
configs/kernel-aarch64-64k-rhel.config:CONFIG_USB_VIDEO_CLASS=m …

[LTS 9.4] media: uvcvideo: Remove dangling pointers

---

include/linux/netdevice.h
include/net/net_namespace.h
net/ipv6/ndisc.c

[LTS 9.4]
CVE-2025-21764
VULN-54027
<https://access.redhat.com/security/cve/CVE-2025-21764>
> A vulnerability was found in the Linux kernel's IPv6 Neighbor Discovery (NDISC) subsystem, which manages network neighbor information. The issue arises from improper synchronization mechanisms when allocating socket buffers (sk\_buff) in the ndisc\_alloc\_skb() function. Specifically, the function can be called without holding the necessary Read-Copy-Update (RCU) or Routing Netlink (RTNL) locks, leading to a potential use-after-free (UAF) condition. This flaw allows an attacker with local access and low privileges to exploit the race condition, potentially causing system instability or crashes.
The mainline fix 628e6d18930bbd21f2d4562228afe27694f66da9 uses `dev_net_rcu(…)` function defined in …

[LTS 9.4] ndisc: use RCU protection in ndisc_alloc_skb()

---

arch/x86/include/asm/kvm_host.h
arch/x86/kvm/svm/svm.c
arch/x86/kvm/vmx/vmx.c
arch/x86/kvm/x86.c
kernel/time/posix-cpu-timers.c
net/core/devlink.c
net/wireless/scan.c

```
wifi: cfg80211: fix u8 overflow in cfg80211_update_notlisted_nontrans()
jira VULN-3805
cve CVE-2022-41674
commit-author Johannes Berg <johannes.berg@intel.com>
commit aebe9f4639b13a1f4e9a6b42cdd2e38c617b442d
```
```
KVM: x86: do not report a vCPU as preempted outside instruction boundaries
jira VULN-3802
cve CVE-2022-39189
commit-author Paolo Bonzini <pbonzini@redhat.com>
commit 6cd88243c7e03845a450795e134b488fc2afb736
```
```
devlink: Fix use-after-free after a failed reload
jira VULN-3798
cve CVE-2022-3625
commit-author Ido Schimmel <idosch@nvidia.com>
commit 6b4db2e528f650c7fb712961aac36455468d5902
```
```
posix-cpu-timers: fix race between handle_posix_cpu_timers() and posix_cpu_timer_del()
jira VULN-136688
cve CVE-2025-38352
commit-author Oleg Nesterov <oleg@redhat.com>
commit …
```

[lts86] Many VULNs 9-9-25

---

include/net/sch_generic.h
net/sched/cls_api.c
net/sched/cls_flower.c

[LTS 9.4]
CVE-2024-26669
VULN-8198
<https://web.git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=32f2a0afa95fae0d1ceec2ff06e0e816939964b8>
> net/sched: flower: Fix chain template offload
> 
> When a qdisc is deleted from a net device the stack instructs the
> underlying driver to remove its flow offload callback from the
> associated filter block using the 'FLOW\_BLOCK\_UNBIND' command. The stack
> then continues to replay the removal of the filters in the block for
> this driver by iterating over the chains in the block and invoking the
> 'reoffload' operation of the classifier being used. In turn, the
> classifier in its 'reoffload' operation prepares and emits a
> 'FLOW\_CLS\_DESTROY' command for each filter.
> 
> However, the stack does not do the same for chain …

[LTS 9.4] net/sched: flower: Fix chain template offload

---

drivers/gpu/drm/amd/amdgpu/amdgpu_mes.c
drivers/net/ethernet/mellanox/mlx5/core/en_rx.c
drivers/net/wireless/realtek/rtw89/debug.c
fs/ext4/resize.c
fs/xfs/libxfs/xfs_dir2_data.c
fs/xfs/libxfs/xfs_dir2_priv.h
kernel/bpf/verifier.c
net/core/net_namespace.c
net/ipv4/ip_tunnel_core.c
net/iucv/iucv.c
net/mptcp/pm_netlink.c
net/tipc/udp_media.c
security/keys/keyring.c

```
bpf: Don't use tnum_range on array range checking for poke descriptors
jira VULN-141362
jira VULN-136651
cve CVE-2022-49985
commit-author Daniel Borkmann <daniel@iogearbox.net>
commit a657182a5c5150cdfacb6640aad1d2712571a409
```
```
ext4: avoid resizing to a partial cluster size
jira VULN-141447
jira VULN-69320
cve CVE-2022-50020
commit-author Kiselev, Oleg <okiselev@amazon.com>
commit 69cb8e9d8cd97cdf5e293b26d70a9dee3e35e6bd
```
```
tunnels: fix out of bounds access when building IPv6 PMTU error
jira VULN-8933
jira VULN-8932
cve CVE-2024-26665
commit-author Antoine Tenart <atenart@kernel.org>
commit d75abeec401f8c86b470e7028a13fcdc87e5dd06
```
```
net: fix out-of-bounds access in ops_init
jira VULN-8955
jira VULN-8954
cve CVE-2024-36883
commit-author Thadeu Lima de Souza Cascardo …
```

[FIPS 8.6/8.10 compliant] Batch of 12 2025-09-12

---

crypto/algif_hash.c
drivers/net/wireless/realtek/rtw88/coex.c
fs/locks.c
kernel/padata.c
net/core/net_namespace.c
net/ipv4/tcp_ipv4.c
net/ipv6/route.c
net/mptcp/pm_netlink.c
net/netfilter/nft_exthdr.c
net/sched/sch_hfsc.c
net/sched/sch_multiq.c
net/tipc/topsrv.c

```
tipc: Fix use-after-free in tipc_conn_close().
jira VULN-80318
cve CVE-2025-38464
commit-author Kuniyuki Iwashima <kuniyu@google.com>
commit 667eeab4999e981c96b447a4df5f20bdf5c26f13
```
```
sch_hfsc: make hfsc_qlen_notify() idempotent
jira VULN-71949
cve CVE-2025-38177
commit-author Cong Wang <xiyou.wangcong@gmail.com>
commit 51eb3b65544c9efd6a1026889ee5fb5aa62da3bb
```
```
wifi: rtw88: fix the 'para' buffer size to avoid reading out of bounds
jira VULN-71888
cve CVE-2025-38159
commit-author Alexey Kodanev <aleksei.kodanev@bell-sw.com>
commit 4c2c372de2e108319236203cce6de44d70ae15cd
```
```
crypto: algif_hash - fix double free in hash_accept
jira VULN-70979
cve CVE-2025-38079
commit-author Ivan Pravdin <ipravdin.official@gmail.com>
commit b2df03ed4052e97126267e8c13ad4204ea6ba9b6
``` …

[lts92] Many VULNs 9-15-25

---

crypto/algif_hash.c
drivers/memstick/host/rtsx_usb_ms.c
drivers/net/ethernet/intel/i40e/i40e_common.c
drivers/net/usb/ch9200.c
drivers/net/usb/smsc75xx.c
drivers/net/wireless/realtek/rtw88/coex.c
fs/ext4/namei.c
fs/ext4/xattr.c
include/linux/netdevice.h
include/net/net_namespace.h
kernel/sched/fair.c
net/atm/lec.c
net/ipv6/ndisc.c
net/sched/sch_ets.c

34e856a4e463f83e1800cd24f8f5dcc287a1d4cd - net: add dev_net_rcu() helper
ed1ca9d753deda057f8ac37bca55b501a67e7c6e - net: treat possible_net_t net pointer as an RCU one and add read_pnet_rcu()
Are both preconditions to 
47873647b609a65c844c7ebfed160259cde2f719 - ndisc: use RCU protection in ndisc_alloc_skb()
This are in the latest 8.10 as well
The security team @jason-rodri and @jallisonciq  have discussed this that and that it does not impact certification as this is not touching any math but would like either of them to sign off on this.
64ea2c322637239ada43691cd935fe650f834843 - crypto: algif_hash - fix double free in hash_accept
```
--- a/crypto/algif_hash.c
+++ b/crypto/algif_hash.c
@@ -267,10 +267,6 @@ static int hash_accept(struct socket *sock, struct socket *newsock, int flags, …
```

[FIPS-8-Compliant] batch 12 fips-8-compliant/4.18.0-553.16.1

---

fs/ext4/ext4.h
fs/ext4/ext4_jbd2.h
fs/ext4/inode.c
fs/ext4/super.c
fs/ext4/xattr.c
fs/ext4/xattr.h

[LTS 9.4]
CVE-2025-22121 VULN-65381
CVE-2025-22113 VULN-65358
7e3df3850b9ce8f89d636c2fa42e9220dba979c4:
ext4: introduce ITAIL helper
jira VULN-65381
cve-pre CVE-2025-22121
commit-author Ye Bin <yebin10@huawei.com>
commit 69f3a3039b0d0003de008659cafd5a1eaaa0a7a4
18ee55af91163d10f82e80c658cc9eeffff7bc25:
ext4: fix out-of-bound read in ext4_xattr_inode_dec_ref_all()
jira VULN-65381
cve CVE-2025-22121
commit-author Ye Bin <yebin10@huawei.com>
commit 5701875f9609b000d91351eaa6bfd97fe2f157f4
The mainline fix 5701875f9609b000d91351eaa6bfd97fe2f157f4 conflicts without 69f3a3039b0d0003de008659cafd5a1eaaa0a7a4. The cve-pre is a previous commit right before 5701875f9609b000d91351eaa6bfd97fe2f157f4 in kernel's history, in fact they were commited at the same time and have the same author, suggesting …

[LTS 9.4] CVE-2025-22113, CVE-2025-22121

---

fs/nfsd/stats.c

[LTS 9.4]
CVE-2025-22026
VULN-64896
<https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=930b64ca0c511521f0abdd1d57ce52b2a6e3476b>
> nfsd: don't ignore the return code of svc\_proc\_register()
> 
> Currently, nfsd\_proc\_stat\_init() ignores the return value of
> svc\_proc\_register(). If the procfile creation fails, then the kernel
> will WARN when it tries to remove the entry later.
> 
> Fix nfsd\_proc\_stat\_init() to return the same type of pointer as
> svc\_proc\_register(), and fix up nfsd\_net\_init() to check that and fail
> the nfsd\_net construction if it occurs.
> 
> svc\_proc\_register() can fail if the dentry can't be allocated, or if an
> identical dentry already exists. The second case is pretty unlikely in
> the nfsd\_net construction codepath, so …

[LTS 9.4] nfsd: don't ignore the return code of svc_proc_register()

---

drivers/infiniband/core/iwcm.c
include/net/sock.h
net/bpf/test_run.c
net/core/sock.c
net/ipv4/tcp_output.c
net/ipv4/udp.c
net/mptcp/protocol.c

* Backporting 6b3d638ca897e099fa99bd6d02189d3176f80a47 to address CVE-2025-21867 required prerequisite commit d3fd203f36d46aa29600a72d57a1b61af80e4a25 which is associated with CVE-2022-49840
* Backporting 6883b680e703c6b2efddb4e7a8d891ce1803d06b to address CVE-2025-38211 required prerequisite commit aee2424246f9f1dadc33faa78990c1e2eb7826e4 which is associated with CVE-2024-42285, and had an upstream fix in 86dfdd8288907f03c18b7fb462e0e232c4f98d89 which is associated with CVE-2024-47696
* Backporting df207de9d9e7a4d92f8567e2c539d9c8c12fd99d to address CVE-2025-22058 requried prerequisite commits 6c302e799a0d4be1362f505453b714fe05d91f2a and 5e6300e7b3a4ab5b72a82079753868e91fbf9efc
```
bpf, test_run: Fix alignment problem in bpf_prog_test_run_skb()
jira VULN-66054
cve CVE-2022-49840 …
```

[lts92] Many VULNs 9-22-25

---

arch/x86/kernel/cpu/common.c
drivers/infiniband/hw/mana/main.c
drivers/net/ethernet/microsoft/Kconfig
drivers/net/ethernet/microsoft/mana/gdma_main.c
drivers/net/ethernet/microsoft/mana/hw_channel.c
drivers/net/ethernet/microsoft/mana/mana_en.c
drivers/net/ethernet/microsoft/mana/shm_channel.c
include/net/mana/gdma.h
include/net/mana/mana.h

* Create `sig-cloud-8/4.18.0-553.74.1.el8_10` branch
None
```
shreeya@spatel-dev-bom:~/ciq/workspace/sig-cloud-8/kernel-src-tree-tools$ python3 rolling-release-update.py --repo ../kernel-src-tree/ \
--new-base-branch rocky8_10 \
--old-rolling-branch sig-cloud-8/4.18.0-553.72.1.el8_10
[rolling release update] Checking out branch:  sig-cloud-8/4.18.0-553.72.1.el8_10
b'06a1b8b22bc2 (tag: …
```

[SIG-CLOUD-8] Rebase custom changes to kernel-4.18.0-553.74.1.el8_10

---

drivers/hv/channel.c
drivers/infiniband/hw/mana/device.c
drivers/infiniband/hw/mana/mana_ib.h
drivers/net/ethernet/microsoft/mana/gdma_main.c
drivers/net/ethernet/microsoft/mana/hw_channel.c
drivers/net/ethernet/microsoft/mana/mana_en.c
drivers/net/ethernet/microsoft/mana/mana_ethtool.c
drivers/net/hyperv/hyperv_net.h
drivers/net/hyperv/netvsc.c
drivers/net/hyperv/netvsc_drv.c
drivers/net/hyperv/rndis_filter.c
drivers/scsi/storvsc_drv.c
include/linux/hyperv.h
include/net/mana/gdma.h
include/net/mana/mana.h
tools/hv/hv_kvp_daemon.c

* Create `sig-cloud-10/6.12.0-55.X.1.el10_0` branch
None
```
[jmaple@devbox code]$ cat RR.resf_kernel-6.12.0-55.32.1.el10_0_out.log
[rolling release update] Rolling Product:  sig-cloud-10
[rolling release update] Checking out branch:  sig-cloud-10/6.12.0-55.30.1.el10_0
b'0b50c952cd24 (tag: resf_kernel-6.12.0-55.30.1.el10_0) Rebuild rocky10_0 with kernel-6.12.0-55.30.1.el10_0'
b'065ddba2712a (tag: resf_kernel-6.12.0-55.29.1.el10_0) Rebuild rocky10_0 with …
```

[SIG-CLOUD-10] Rebase custom changes to 6.12.0-55.32.1.el10_0

---

net/wireless/scan.c

[LTS 8.6]
CVE-2022-42720
VULN-3807
<https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=0b7808818cb9df6680f98996b8e9a439fa7bcc2f>
> wifi: cfg80211: fix BSS refcounting bugs
> 
> There are multiple refcounting bugs related to multi-BSSID:
>  - In bss\_ref\_get(), if the BSS has a hidden\_beacon\_bss, then
>    the bss pointer is overwritten before checking for the
>    transmitted BSS, which is clearly wrong. Fix this by using
>    the bss\_from\_pub() macro.
> 
>  - In cfg80211\_bss\_update() we copy the transmitted\_bss pointer
>    from tmp into new, but then if we release new, we'll unref
>    it erroneously. We already set the pointer and ref it, but
>    need to NULL it since it was copied from the tmp data.
> 
>  - In cfg80211\_inform\_single\_bss\_data(), if …

[LTS 8.6] CVE-2022-42720

---

arch/x86/include/asm/cpu_entry_area.h
arch/x86/include/asm/kasan.h
arch/x86/include/asm/pgtable_32_types.h
arch/x86/mm/cpu_entry_area.c
arch/x86/mm/kasan_init_64.c

[LTS 8.6]
CVE-2023-0597
VULN-3958
<https://access.redhat.com/security/cve/CVE-2023-0597>
> A possible unauthorized memory access flaw was found in the Linux kernel cpu\_entry\_area mapping of X86 CPU data to memory, where a user may guess the location of exception stack(s) or other important data. This issue could allow a local user to gain access to some important data with expected location in memory.
This flaw is independent of any config options and affects all x86 kernels. The commit 97e3d26b5e5f371b3ee223d94dd123e6c442ba80 solving the issue is absent from `ciqlts8_6`'s history, along with other accompanying changes (see [Solution](#orgfd49027)). Additionally, the options settings for related randomization techniques found in `configs/kernel-x86_64.config` …

[LTS 8.6] CVE-2023-0597

---

drivers/misc/vmw_vmci/vmci_queue_pair.c
drivers/scsi/lpfc/lpfc_sli.c
fs/ext4/namei.c
net/sched/sch_hfsc.c

```
misc/vmw_vmci: fix an infoleak in vmci_host_do_receive_datagram()
jira VULN-65834
cve CVE-2022-49788
commit-author Alexander Potapenko <glider@google.com>
commit e5b0d06d9b10f5f43101bd6598b076c347f9295f
```
```
ext4: fix off-by-one error in do_split
jira VULN-66668
cve CVE-2025-23150
commit-author Artem Sadovnikov <a.sadovnikov@ispras.ru>
commit 94824ac9a8aaf2fb3c54b4bdde842db80ffa555d
```
```
sch_hfsc: make hfsc_qlen_notify() idempotent
jira VULN-71943
cve CVE-2025-38177
commit-author Cong Wang <xiyou.wangcong@gmail.com>
commit 51eb3b65544c9efd6a1026889ee5fb5aa62da3bb
```
```
scsi: lpfc: Use memcpy() for BIOS version
jira VULN-72452
cve CVE-2025-38332
commit-author Daniel Wagner <wagi@kernel.org>
commit ae82eaf4aeea060bb736c3e20c0568b67c701d7d
```
``` …
```

[cbr79] Many VULNs 9-26-25

---

fs/ext4/ext4.h
fs/ext4/ext4_jbd2.h
fs/ext4/inline.c
fs/ext4/inode.c
fs/ext4/super.c
fs/ext4/xattr.c
fs/ext4/xattr.h

For CVE-2025-22121 and CVE-2025-22113 see @pvts-mat write-up in https://github.com/ctrliq/kernel-src-tree/pull/577  The same 5 commits where backported here PLUS the additional prerequisite commit 3478c83cf26bbffd026ae6a56bcb1fe544f0834e for CVE-2025-22121.
2b96b4a5d9443ca4cad58b0040be455803c05a42 was backported to address CVE-2023-53100 which requied prerequisite commit 1dcdce5919115a471bf4921a57f20050c545a236
```
ext4: move where set the MAY_INLINE_DATA flag is set
jira VULN-67318
cve-pre CVE-2023-53100
commit-author Ye Bin <yebin10@huawei.com>
commit 1dcdce5919115a471bf4921a57f20050c545a236
```
```
ext4: fix WARNING in ext4_update_inline_data
jira VULN-67318
cve CVE-2023-53100
commit-author Ye Bin <yebin10@huawei.com>
commit 2b96b4a5d9443ca4cad58b0040be455803c05a42
```
```
ext4: …
```

[lts92] Many VULNs 9-26-25

---

fs/namespace.c
net/core/filter.c
net/ipv4/udp_offload.c
net/vmw_vsock/af_vsock.c

```
use uniform permission checks for all mount propagation changes
jira VULN-98606
jira VULN-98607
cve-bf CVE-2025-38498
commit-author Al Viro <viro@zeniv.linux.org.uk>
commit cffd0441872e7f6b1fce5e78fb1c99187a291330
upstream-diff This is a partial backport due to missing 9ffb14ef61ba
which introduces do_set_group(). This is where the below
operation on diffferent aspects of the same thing is introduced.
This change does however introduce some additional safety checks
which should be considered.
```
```
net: fix udp gso skb_segment after pull from frag_list
jira VULN-156444
jira VULN-156445
cve CVE-2025-38124
commit-author Shiming Cheng <shiming.cheng@mediatek.com>
commit 3382a1ed7f778db841063f5d7e317ac55f9e7f72
```
```
bpf: Fix a segment issue when downgrading gso_size
jira VULN-38750 …
```

[FIPS 8 Compliant] Many CVES

---

net/core/filter.c
net/ipv4/udp_offload.c

```
net: fix udp gso skb_segment after pull from frag_list
jira VULN-71810
cve CVE-2025-38124
commit-author Shiming Cheng <shiming.cheng@mediatek.com>
commit 3382a1ed7f778db841063f5d7e317ac55f9e7f72
```
```
gso: fix udp gso fraglist segmentation after pull from frag_list
jira VULN-45771
cve CVE-2024-49978
commit-author Willem de Bruijn <willemb@google.com>
commit a1e40ac5b5e9077fe1f7ae0eb88034db0f9ae1ab
```
```
bpf: Fix a segment issue when downgrading gso_size
jira VULN-38755
cve CVE-2024-42281
commit-author Fred Li <dracodingfly@gmail.com>
commit fa5ef655615a01533035c6139248c5b33aa27028
```
```
[jmaple@devbox code]$ egrep -B 5 -A 5 "\[TIMER\]|^Starting Build" $(ls -t kbuild* | head -n1)
Running make mrproper...
[TIMER]{MRPROPER}: 5s
x86_64 architecture …
```

[FIPS 9.2] gro / gso CVEs

---

drivers/hv/channel.c
drivers/infiniband/hw/mana/device.c
drivers/infiniband/hw/mana/main.c
drivers/infiniband/hw/mana/mana_ib.h
drivers/net/ethernet/microsoft/mana/gdma_main.c
drivers/net/ethernet/microsoft/mana/hw_channel.c
drivers/net/ethernet/microsoft/mana/mana_en.c
drivers/net/ethernet/microsoft/mana/mana_ethtool.c
drivers/net/hyperv/hyperv_net.h
drivers/net/hyperv/netvsc.c
drivers/net/hyperv/netvsc_drv.c
drivers/net/hyperv/rndis_filter.c
drivers/scsi/storvsc_drv.c
include/linux/hyperv.h
include/net/mana/gdma.h
include/net/mana/mana.h
tools/hv/hv_kvp_daemon.c
tools/testing/selftests/mm/hmm-tests.c

* Create `sig-cloud-9/5.14.0-570.X.1.el9_6` branch
None
```
hreeya@spatel-dev-bom:~/ciq/workspace/sig-cloud-9/kernel-src-tree-tools$ python3 rolling-release-update.py --repo ../kernel-src-tree/ --new-base-branch rocky9_6 --old-rolling-branch sig-cloud-9/5.14.0-570.42.2.el9_6
[rolling release update] Checking out branch:  sig-cloud-9/5.14.0-570.42.2.el9_6
b'4eb20e218dc1 (tag: resf_kernel-5.14.0-570.42.2.el9_6, …
```

[SIG-CLOUD-9] rebase custom changes to kernel-5.14.0-570.49.1.el9_6
